# -*- coding: utf-8 -*-
"""Disease NSCLC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14b4X0Qfl-pNzTeq7dZP_w3k4-aXHGqtJ

# **DISEASE NSCLC**
"""

import requests
import time
import xml.etree.ElementTree as ET
import csv

def fetch_pubmed_ids(term, retmax=100, retstart=0):
    """Ambil daftar PMID dari PubMed berdasarkan istilah pencarian."""
    base = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
    params = {
        "db": "pubmed",
        "term": term,
        "retmax": retmax,
        "retstart": retstart,
        "retmode": "xml"
    }
    resp = requests.get(base, params=params)
    resp.raise_for_status()
    root = ET.fromstring(resp.text)
    idlist = [id_el.text for id_el in root.findall(".//IdList/Id")]
    return idlist

def fetch_pubmed_article(pmid):
    """Ambil metadata artikel (judul, abstrak, MeSH terms) berdasarkan PMID."""
    base = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
    params = {
        "db": "pubmed",
        "id": pmid,
        "retmode": "xml",
        "rettype": "abstract"
    }
    resp = requests.get(base, params=params)
    resp.raise_for_status()
    root = ET.fromstring(resp.text)
    art = {}
    art['PMID'] = pmid
    title_el = root.find(".//ArticleTitle")
    art['Title'] = title_el.text if title_el is not None else ""
    abstract_el = root.find(".//Abstract/AbstractText")
    art['Abstract'] = abstract_el.text if abstract_el is not None else ""
    # MeSH terms
    mesh_terms = [el.text for el in root.findall(".//MeshHeading/DescriptorName")]
    art['MeSH'] = "|".join(mesh_terms)
    return art

def main():
    # Istilah pencarian: NSCLC + comorbidity
    term = "(Non-Small Cell Lung Cancer[MeSH Terms] OR NSCLC) AND comorbidities)"
    pmids = fetch_pubmed_ids(term, retmax=2000)
    print(f"Found {len(pmids)} PMIDs.")

    results = []
    for i, pmid in enumerate(pmids):
        try:
            art = fetch_pubmed_article(pmid)
            results.append(art)
        except Exception as e:
            print(f"Error fetching PMID {pmid}: {e}")
        time.sleep(0.34)  # agar tidak kena rate limit

    # Simpan ke CSV
    keys = ['PMID', 'Title', 'Abstract', 'MeSH']
    with open("/content/drive/MyDrive/dataset/Tesis/pubtator/nsclc_comorbidity_pubmed.csv", "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        for art in results:
            writer.writerow({k: art.get(k, "") for k in keys})

    print("Done. CSV tersimpan.")

if __name__ == "__main__":
    main()

import csv
import time
import requests

input_file = "/content/drive/MyDrive/dataset/Tesis/pubtator/nsclc_comorbidity_pubmed.csv"
output_file = "/content/drive/MyDrive/dataset/Tesis/pubtator/nsclc_unique_diseases_pubtator.txt"
output_detail_file = "/content/drive/MyDrive/dataset/Tesis/pubtator/nsclc_disease_annotations_pubtator.csv"

def load_pmids_from_csv(input_file):
    """Ambil PMID dari file CSV hasil PubMed."""
    pmids = []

    with open(input_file, "r", encoding="utf-8") as infile:
        sample = infile.read(2048)
        dialect = csv.Sniffer().sniff(sample)
        infile.seek(0)

        reader = csv.DictReader(infile, dialect=dialect)

        for row in reader:
            pmid = row.get("PMID", "").strip()
            if pmid:
                pmids.append(pmid)

    return list(dict.fromkeys(pmids))  # hapus duplikat, tetap urut


def fetch_pubtator_annotations(pmids):
    """
    Ambil anotasi PubTator berdasarkan PMID.
    Format yang digunakan: pubtator.
    """

    url = "https://www.ncbi.nlm.nih.gov/research/pubtator3-api/publications/export/pubtator"

    params = {
        "pmids": ",".join(pmids)
    }

    response = requests.get(url, params=params, timeout=60)
    response.raise_for_status()

    return response.text


def parse_disease_annotations(pubtator_text):
    """
    Ekstrak anotasi bertipe Disease dari format PubTator.

    Format umum baris anotasi PubTator:
    PMID    start    end    mention    type    identifier

    Contoh:
    12345678    10    24    lung cancer    Disease    MESH:D008175
    """

    disease_annotations = []

    for line in pubtator_text.splitlines():
        line = line.strip()

        if not line:
            continue

        parts = line.split("\t")

        # Baris judul/abstrak biasanya formatnya:
        # PMID|t|Title
        # PMID|a|Abstract
        # Jadi dilewati.
        if len(parts) < 5:
            continue

        pmid = parts[0]
        mention = parts[3].strip()
        entity_type = parts[4].strip()

        identifier = ""
        if len(parts) >= 6:
            identifier = parts[5].strip()

        if entity_type.lower() == "disease" and mention:
            disease_annotations.append({
                "PMID": pmid,
                "Disease_Mention": mention,
                "Entity_Type": entity_type,
                "Identifier": identifier
            })

    return disease_annotations


def main():
    pmids = load_pmids_from_csv(input_file)
    print(f"Total PMID ditemukan: {len(pmids)}")

    unique_diseases = set()
    all_annotations = []

    batch_size = 100

    for i in range(0, len(pmids), batch_size):
        batch_pmids = pmids[i:i + batch_size]
        print(f"Memproses batch {i // batch_size + 1}: {len(batch_pmids)} PMID")

        try:
            pubtator_text = fetch_pubtator_annotations(batch_pmids)
            disease_annotations = parse_disease_annotations(pubtator_text)

            for ann in disease_annotations:
                unique_diseases.add(ann["Disease_Mention"])
                all_annotations.append(ann)

        except Exception as e:
            print(f"Error pada batch {i // batch_size + 1}: {e}")

        time.sleep(1)  # jeda agar tidak terlalu sering request

    # Simpan daftar penyakit unik
    with open(output_file, "w", encoding="utf-8") as outfile:
        for disease in sorted(unique_diseases):
            outfile.write(disease + "\n")

    # Simpan detail anotasi penyakit
    with open(output_detail_file, "w", newline="", encoding="utf-8") as outfile:
        fieldnames = ["PMID", "Disease_Mention", "Entity_Type", "Identifier"]
        writer = csv.DictWriter(outfile, fieldnames=fieldnames)
        writer.writeheader()

        for ann in all_annotations:
            writer.writerow(ann)

    print("✅ Selesai.")
    print(f"Total disease mention unik: {len(unique_diseases)}")
    print(f"File penyakit unik: {output_file}")
    print(f"File detail anotasi: {output_detail_file}")


if __name__ == "__main__":
    main()

import requests

def get_doid(disease_name, api_key):
    url = "http://data.bioontology.org/search"
    params = {
        'q': disease_name,
        'apikey': api_key,
        'ontologies': 'DOID',
        'require_exact_match': 'false'
    }

    response = requests.get(url, params=params)

    if response.status_code == 200:
        try:
            results = response.json()
            collection = results.get('collection', [])
            if collection:
                first_result = collection[0]
                label = first_result.get('prefLabel', disease_name)
                doid_url = first_result.get('@id', '')
                doid = doid_url.split('/')[-1] if doid_url else 'No DOID found'
                return label, doid
            else:
                return disease_name, "No DOID found"
        except ValueError:
            return disease_name, "Failed to decode JSON"
    else:
        return disease_name, f"Error: {response.status_code}"

API_KEY = '***'

input_file_path = '/content/drive/MyDrive/dataset/Tesis/nsclc_unique_diseases_pubtator.txt'
output_file_path = '/content/drive/MyDrive/dataset/Tesis/3_pubtator_ids.txt'

with open(input_file_path, 'r', encoding='utf-8') as file:
    disease_names = [line.strip() for line in file if line.strip()]

with open(output_file_path, 'w', encoding='utf-8') as file:
    for disease_name in disease_names:
        name, doid = get_doid(disease_name, API_KEY)
        file.write(f"{name}: {doid}\n")

print("✅ Proses pencarian selesai.")
print(f"Total disease names processed: {len(disease_names)}")
print(f"Hasil disimpan di {output_file_path}")

# Path input dan output
input_file = '/content/drive/MyDrive/dataset/Tesis/3_pubtator_ids.txt'
output_file = '/content/drive/MyDrive/dataset/Tesis/3_pubtator_ids_cleaned.txt'
doid_only_file = '/content/drive/MyDrive/dataset/Tesis/doidnsclc_pubtator.txt'

unique_lines = set()

with open(input_file, 'r', encoding='utf-8') as infile:
    for line in infile:
        line = line.strip()
        if "DOID_" in line:
            unique_lines.add(line)

# Simpan hasil bersih
with open(output_file, 'w', encoding='utf-8') as outfile:
    for line in sorted(unique_lines):
        outfile.write(line + '\n')

# Simpan hanya DOID-nya saja (tanpa awalan teks)
doid_only = []
for line in unique_lines:
    if "DOID_" in line:
        doid = line.split("DOID_")[-1]  # ambil angka setelah DOID_
        doid_only.append("DOID_" + doid)

with open(doid_only_file, 'w', encoding='utf-8') as outfile:
    for doid in sorted(doid_only):
        outfile.write(doid + '\n')

print(f"✅ File berhasil dibersihkan dan disimpan ke {output_file}")
print(f"✅ File DOID-only disimpan ke {doid_only_file}")
print(f"Total entri unik dengan DOID: {len(unique_lines)}")

import os
import re
import time
import csv
import requests
from urllib.parse import quote

os.environ["BIOPORTAL_API_KEY"] = "**"

# =====================
# INPUT / OUTPUT
# =====================
INPUT_FILE = "/content/drive/MyDrive/dataset/Tesis/doidnsclc_pubtator.txt"

OUT_KEPT = "/content/drive/MyDrive/dataset/Tesis/doidnsclc_after_layer2_kept_pubtator.txt"
OUT_REMOVED_L2 = "/content/drive/MyDrive/dataset/Tesis/doidnsclc_removed_layer2_pubtator.txt"
OUT_AUDIT = "/content/drive/MyDrive/dataset/Tesis/doidnsclc_audit_layer2_pubtator.csv"

# =====================
# BIOPORTAL CONFIG
# =====================
API_KEY = os.getenv("BIOPORTAL_API_KEY")
BASE = "https://data.bioontology.org"
ONTOLOGY = "DOID"

LAYER1_PARENTS = [
    "DOID:1324",   # lung cancer
    "DOID:3908",   # non-small cell lung carcinoma / NSCLC
    "DOID:162",    # cancer
]

# =====================
# MANUAL BLACKLIST DOID
# =====================
EXPLICIT_REMOVE_DOIDS = {
    "DOID:4",        # Disease
    "DOID:0050685",  # Small cell carcinoma
    "DOID:305",      # Carcinoma
}

# =====================
# LAYER-2 RULES
# =====================

GENERIC_LABEL_PATTERNS = [
    r"\bchromosomal\b",
    r"\bgenetic\b",
    r"\bcongenital\b",
    r"\bdevelopmental\b",
    r"\bprimary immunodeficiency\b",
    r"\bimmunodeficiency\b",
    r"\btelomere\b",
    r"\bsyndrome\b",
    r"\bdeficiency\b",
]

BLACKLIST_ANCESTOR_LABELS = {
    "chromosomal disease",
    "genetic disease",
    "congenital disease",
    "developmental disorder",
    "primary immunodeficiency disease",
    "telomere biology disorder",
}

MIN_ANCESTOR_COUNT = 0

_label_cache = {}
_anc_label_cache = {}

# =====================
# HELPERS
# =====================
def require_api_key():
    if not API_KEY:
        raise RuntimeError(
            "BIOPORTAL_API_KEY belum diset.\n"
            "Di Colab jalankan:\n"
            "os.environ['BIOPORTAL_API_KEY'] = 'API_KEY_ANDA'"
        )

def normalize_doid(line: str) -> str | None:
    s = line.strip()
    if not s:
        return None

    # Tangani format DOID_123, DOID:123, atau URI BioPortal/OBO
    match = re.search(r"DOID[:_](\d+)", s)
    if not match:
        return None

    num = match.group(1)

    # Pertahankan leading zero, misalnya DOID:0050685
    return f"DOID:{num}"

def doid_colon_to_uri(doid_colon: str) -> str:
    return f"http://purl.obolibrary.org/obo/{doid_colon.replace(':', '_')}"

def bp_get(url: str, params=None, retry=3):
    require_api_key()
    headers = {"Authorization": f"apikey token={API_KEY}"}

    last_response = None

    for i in range(retry):
        r = requests.get(url, headers=headers, params=params, timeout=60)
        last_response = r

        if r.status_code in (429, 500, 502, 503, 504):
            time.sleep(1.5 * (i + 1))
            continue

        r.raise_for_status()
        return r.json()

    last_response.raise_for_status()

def extract_doid_from_uri(uri: str) -> str | None:
    match = re.search(r"DOID_(\d+)", uri)
    if not match:
        return None
    return f"DOID:{match.group(1)}"

def fetch_descendants(parent_doid_colon: str) -> set[str]:
    parent_uri = quote(doid_colon_to_uri(parent_doid_colon), safe="")
    url = f"{BASE}/ontologies/{ONTOLOGY}/classes/{parent_uri}/descendants"

    descendants = set()
    next_url = url

    while next_url:
        data = bp_get(next_url)

        if isinstance(data, dict):
            items = data.get("collection", [])
            next_url = data.get("links", {}).get("next")
        elif isinstance(data, list):
            items = data
            next_url = None
        else:
            items = []
            next_url = None

        for item in items:
            if not isinstance(item, dict):
                continue

            cid = item.get("@id", "")
            doid = extract_doid_from_uri(cid)

            if doid:
                descendants.add(doid)

    return descendants

def fetch_pref_label(doid_colon: str) -> str | None:
    if doid_colon in _label_cache:
        return _label_cache[doid_colon]

    uri = quote(doid_colon_to_uri(doid_colon), safe="")
    url = f"{BASE}/ontologies/{ONTOLOGY}/classes/{uri}"

    data = bp_get(url)
    label = data.get("prefLabel")

    _label_cache[doid_colon] = label
    return label

def fetch_ancestor_labels(doid_colon: str) -> list[str]:
    if doid_colon in _anc_label_cache:
        return _anc_label_cache[doid_colon]

    uri = quote(doid_colon_to_uri(doid_colon), safe="")
    url = f"{BASE}/ontologies/{ONTOLOGY}/classes/{uri}/ancestors"

    data = bp_get(url)

    if isinstance(data, dict):
        items = data.get("collection", [])
    elif isinstance(data, list):
        items = data
    else:
        items = []

    labels = []

    for item in items:
        if isinstance(item, dict):
            lab = item.get("prefLabel")
            if lab:
                labels.append(lab.strip().lower())

    _anc_label_cache[doid_colon] = labels
    return labels

def matches_generic_label(label: str | None) -> bool:
    if not label:
        return False

    l = label.lower()

    for pat in GENERIC_LABEL_PATTERNS:
        if re.search(pat, l):
            return True

    return False

def has_blacklisted_ancestor(anc_labels: list[str]) -> str | None:
    s = set(anc_labels)

    for bad in BLACKLIST_ANCESTOR_LABELS:
        if bad in s:
            return bad

    return None

# =====================
# MAIN
# =====================

# 1) Load input DOIDs
doids = set()

with open(INPUT_FILE, "r", encoding="utf-8") as f:
    for line in f:
        d = normalize_doid(line)
        if d:
            doids.add(d)

print(f"Input DOID unik: {len(doids)}")

# 2) Layer 1: remove descendants of lung cancer / NSCLC / cancer
layer1_remove_set = set()

for p in LAYER1_PARENTS:
    print(f"Mengambil descendants dari {p} ...")
    layer1_remove_set |= fetch_descendants(p)

# Tambahkan parent itu sendiri agar ikut terhapus jika muncul di input
layer1_remove_set |= set(LAYER1_PARENTS)

layer1_removed = sorted([d for d in doids if d in layer1_remove_set])
layer1_kept = sorted([d for d in doids if d not in layer1_remove_set])

print(f"Layer-1 removed total: {len(layer1_removed)}")
print(f"Layer-1 kept candidates: {len(layer1_kept)}")

# 3) Layer 2: explicit blacklist + generic/umbrella filtering + audit
kept_final = []
removed_l2 = []
audit_rows = []

for d in layer1_kept:
    label = fetch_pref_label(d)
    anc_labels = fetch_ancestor_labels(d)

    reason = None

    # Manual blacklist DOID
    if d in EXPLICIT_REMOVE_DOIDS:
        reason = "explicit_remove:manual_blacklist"

    # Depth filter
    if not reason and MIN_ANCESTOR_COUNT > 0 and len(anc_labels) < MIN_ANCESTOR_COUNT:
        reason = f"too_general_low_depth(<{MIN_ANCESTOR_COUNT})"

    # Ancestor branch filter
    bad_anc = has_blacklisted_ancestor(anc_labels)
    if not reason and bad_anc:
        reason = f"blacklisted_ancestor:{bad_anc}"

    # Label regex filter
    if not reason and matches_generic_label(label):
        reason = "generic_label_pattern"

    if reason:
        removed_l2.append(d)
        audit_rows.append([d, label or "", "REMOVED", reason])
    else:
        kept_final.append(d)
        audit_rows.append([d, label or "", "KEPT", ""])

# 4) Save outputs
with open(OUT_KEPT, "w", encoding="utf-8") as f:
    for d in sorted(kept_final):
        f.write(d + "\n")

with open(OUT_REMOVED_L2, "w", encoding="utf-8") as f:
    for d in sorted(removed_l2):
        f.write(d + "\n")

with open(OUT_AUDIT, "w", encoding="utf-8", newline="") as f:
    w = csv.writer(f)
    w.writerow(["doid", "prefLabel", "status", "reason"])
    w.writerows(audit_rows)

print("✅ Selesai.")
print(f"Kept final: {len(kept_final)} -> {OUT_KEPT}")
print(f"Removed layer-2: {len(removed_l2)} -> {OUT_REMOVED_L2}")
print(f"Audit CSV: {OUT_AUDIT}")