# -*- coding: utf-8 -*-
"""Similarity_SCLC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZgEuGPkVpp3UcIll61kq-xN_3QETrZI
"""

import pandas as pd
import numpy as np
import requests
import itertools
import time
import sys
import re
import os
from urllib.parse import quote

input_file = "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/doidsclc_after_layer2_kept_pubtator.txt"
output_file = "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/doid_sclc_converted.txt"

with open(input_file, "r") as f:
    lines = f.read().splitlines()

converted = [line.strip().replace("_", ":") for line in lines]

remove_ids = {"DOID:4", "DOID:162"}

# Hapus DOID tertentu dan hapus duplikat sambil mempertahankan urutan
seen = set()
converted_filtered = []

for doid in converted:
    if doid in remove_ids:
        continue

    if doid not in seen:
        converted_filtered.append(doid)
        seen.add(doid)

with open(output_file, "w") as f:
    f.write("\n".join(converted_filtered))

print("Selesai. File disimpan sebagai:", output_file)
print("Jumlah data awal:", len(converted))
print("Jumlah data setelah filter dan hapus duplikat:", len(converted_filtered))
print("Jumlah data yang dihapus:", len(converted) - len(converted_filtered))

# ==== KONFIGURASI ====
api_key = os.getenv("BIOPORTAL_API_KEY","b")
input_file = "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/doid_sclc_converted.txt"
output_file = "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/sclc_wangsimilarity_doid.csv"
ontology = "DOID"

BASE_URL = "https://data.bioontology.org"

session = requests.Session()

# ==== UTILITAS ====
def normalize_doid_to_iri(doid):
    """
    Mengubah DOID pendek menjadi full IRI BioPortal/OBO.
    Contoh:
    DOID:9352 -> http://purl.obolibrary.org/obo/DOID_9352
    """
    doid = str(doid).strip()

    if doid.startswith("http://") or doid.startswith("https://"):
        return doid

    if doid.startswith("DOID:"):
        number = doid.replace("DOID:", "")
    elif doid.startswith("DOID_"):
        number = doid.replace("DOID_", "")
    else:
        number = doid

    return f"http://purl.obolibrary.org/obo/DOID_{number}"


def iri_to_doid(iri):
    """
    Mengubah full IRI menjadi DOID pendek.
    Contoh:
    http://purl.obolibrary.org/obo/DOID_9352 -> DOID:9352
    """
    iri = str(iri).strip()
    if "DOID_" in iri:
        return "DOID:" + iri.split("DOID_")[-1]
    return iri


def extract_uri(item):
    """
    Mengambil URI class dari response BioPortal.
    """
    if isinstance(item, dict):
        return item.get("@id") or item.get("id")
    return None


def bioportal_get(url, params=None, max_retries=3):
    """
    Request BioPortal dengan retry sederhana.
    """
    if params is None:
        params = {}

    params = dict(params)
    params["apikey"] = api_key
    params["display_context"] = "false"

    for attempt in range(max_retries):
        try:
            response = session.get(url, params=params, timeout=30)

            if response.status_code == 200:
                return response.json()

            print(f"\n⚠️ HTTP {response.status_code} untuk URL: {url}")
            time.sleep(1 + attempt)

        except requests.exceptions.RequestException as e:
            print(f"\n⚠️ Request error: {e}")
            time.sleep(1 + attempt)

    return None


# ==== AMBIL PATH KE ROOT ====
def get_paths_to_root(doid):
    """
    Mengambil semua path dari suatu DOID ke root menggunakan BioPortal.
    Endpoint ini lebih cocok untuk Wang-like similarity karena kita butuh jarak term ke ancestor.
    """
    class_iri = normalize_doid_to_iri(doid)
    encoded_class_iri = quote(class_iri, safe="")

    url = f"{BASE_URL}/ontologies/{ontology}/classes/{encoded_class_iri}/paths_to_root"
    data = bioportal_get(url)

    if data is None:
        return None

    paths = []

    # BioPortal dapat mengembalikan list langsung atau dict berisi collection.
    if isinstance(data, dict) and "collection" in data:
        data = data["collection"]

    if isinstance(data, list):
        for path in data:
            # Format umum: path adalah list of class objects
            if isinstance(path, list):
                uris = [extract_uri(x) for x in path]
                uris = [u for u in uris if u is not None]
                if uris:
                    paths.append(uris)

            # Antisipasi jika format dibungkus dictionary
            elif isinstance(path, dict):
                possible_path = (
                    path.get("classes")
                    or path.get("path")
                    or path.get("collection")
                    or []
                )
                if isinstance(possible_path, list):
                    uris = [extract_uri(x) for x in possible_path]
                    uris = [u for u in uris if u is not None]
                    if uris:
                        paths.append(uris)

    return paths


# ==== WANG-LIKE SEMANTIC CONTRIBUTION ====
def get_wang_contribution(doid, weight=0.8):
    """
    Menghitung semantic contribution untuk satu DOID.

    Prinsip:
    - DOID itu sendiri diberi kontribusi 1.0.
    - Ancestor yang semakin jauh kontribusinya semakin kecil.
    - weight default 0.8, mengikuti praktik umum Wang similarity untuk relasi is_a.
    """
    class_iri = normalize_doid_to_iri(doid)
    paths = get_paths_to_root(doid)

    if paths is None:
        return None

    contribution = {class_iri: 1.0}

    for path in paths:
        if not path:
            continue

        # Cari posisi term utama dalam path.
        # BioPortal bisa mengembalikan urutan root->term atau term->root,
        # sehingga kita gunakan jarak absolut dari posisi term.
        if class_iri in path:
            self_idx = path.index(class_iri)
        else:
            # fallback jika term utama tidak muncul eksplisit
            self_idx = len(path) - 1

        for idx, ancestor_iri in enumerate(path):
            distance = abs(self_idx - idx)
            value = weight ** distance

            # Jika ancestor muncul dari beberapa path, ambil kontribusi terbesar.
            if ancestor_iri not in contribution:
                contribution[ancestor_iri] = value
            else:
                contribution[ancestor_iri] = max(contribution[ancestor_iri], value)

    return contribution


def wang_similarity(doid_a, doid_b, cache, weight=0.8):
    """
    Menghitung Wang-like similarity antara dua DOID.
    """
    if doid_a not in cache:
        cache[doid_a] = get_wang_contribution(doid_a, weight=weight)
        time.sleep(0.2)

    if doid_b not in cache:
        cache[doid_b] = get_wang_contribution(doid_b, weight=weight)
        time.sleep(0.2)

    contrib_a = cache[doid_a]
    contrib_b = cache[doid_b]

    if contrib_a is None or contrib_b is None:
        return np.nan

    terms_a = set(contrib_a.keys())
    terms_b = set(contrib_b.keys())
    common_terms = terms_a & terms_b

    sv_a = sum(contrib_a.values())
    sv_b = sum(contrib_b.values())

    if sv_a == 0 or sv_b == 0:
        return np.nan

    numerator = sum(contrib_a[t] + contrib_b[t] for t in common_terms)
    denominator = sv_a + sv_b

    return numerator / denominator


# ==== BACA DATA ====
df = pd.read_csv(input_file, header=None, names=["DOID"])

doids = (
    df["DOID"]
    .dropna()
    .astype(str)
    .str.strip()
    .drop_duplicates()
    .tolist()
)

print(f"Jumlah DOID unik: {len(doids)}")

cache = {}

# ==== HITUNG SIMILARITY MATRIX SIMETRIS ====
n = len(doids)
matrix = pd.DataFrame(np.nan, index=doids, columns=doids, dtype=float)

total_pairs = n * (n + 1) // 2
counter = 0

for i, a in enumerate(doids):
    for j in range(i, n):
        b = doids[j]

        sim = wang_similarity(a, b, cache, weight=0.8)

        # Isi dua arah agar matriks simetris
        matrix.loc[a, b] = sim
        matrix.loc[b, a] = sim

        counter += 1
        sys.stdout.write(f"\rSedang memproses pasangan {counter}/{total_pairs}...")
        sys.stdout.flush()

# ==== VALIDASI SEDERHANA ====
print("\n\nValidasi matriks:")

# 1. Cek simetris
is_symmetric = np.allclose(
    matrix.values,
    matrix.values.T,
    equal_nan=True
)
print(f"Matrix symmetric: {is_symmetric}")

# 2. Cek diagonal
diag_values = np.diag(matrix.values)
print(f"Diagonal min: {np.nanmin(diag_values):.4f}")
print(f"Diagonal max: {np.nanmax(diag_values):.4f}")

# 3. Cek apakah ada similarity 1 pada pasangan DOID berbeda
off_diag = matrix.copy()
np.fill_diagonal(off_diag.values, np.nan)

offdiag_ones = np.argwhere(np.isclose(off_diag.values, 1.0, equal_nan=False))

print(f"Off-diagonal similarity = 1.0: {len(offdiag_ones)} pasangan")

if len(offdiag_ones) > 0:
    print("Contoh pasangan off-diagonal bernilai 1.0:")
    for idx_pair in offdiag_ones[:10]:
        r, c = idx_pair
        print(matrix.index[r], "-", matrix.columns[c])

# ==== SIMPAN HASIL ====
matrix.to_csv(output_file)
print(f"\n✅ Selesai! Hasil disimpan di: {output_file}")

# ============================================
# UJI SENSITIVITAS TOPOLOGI BERBASIS THRESHOLD
# ============================================

import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

# ==== KONFIGURASI ====
similarity_file = "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/sclc_wangsimilarity_doid.csv"
output_sensitivity = "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/topologysclc_sensitivity_results.csv"

# Threshold yang akan diuji
thresholds = [0.30, 0.40, 0.50, 0.60, 0.70, 0.80]


# ==== BACA MATRIX SIMILARITY ====
sim_matrix = pd.read_csv(similarity_file, index_col=0)

# Pastikan index dan column berupa string
sim_matrix.index = sim_matrix.index.astype(str)
sim_matrix.columns = sim_matrix.columns.astype(str)

# Isi NaN dengan 0
sim_matrix = sim_matrix.fillna(0)

# ==== BUAT MATRIX MENJADI SIMETRIS ====
# Karena hasil pivot dari combinations_with_replacement biasanya hanya segitiga atas
sim_matrix = sim_matrix.combine_first(sim_matrix.T)
sim_matrix = sim_matrix.fillna(0)

# Pastikan diagonal bernilai 1
np.fill_diagonal(sim_matrix.values, 1.0)


# ==== FUNGSI MEMBENTUK JARINGAN ====
def build_network_from_similarity(sim_matrix, threshold):
    """
    Membentuk jaringan dari matrix similarity.
    Edge dibuat jika similarity >= threshold.
    Self-loop tidak dimasukkan.
    """
    G = nx.Graph()

    nodes = sim_matrix.index.tolist()
    G.add_nodes_from(nodes)

    for i in range(len(nodes)):
        for j in range(i + 1, len(nodes)):
            node_i = nodes[i]
            node_j = nodes[j]
            sim_value = sim_matrix.loc[node_i, node_j]

            if sim_value >= threshold:
                G.add_edge(node_i, node_j, weight=sim_value)

    return G


# ==== FUNGSI HITUNG METRIK TOPOLOGI ====
def calculate_topology_metrics(G, threshold):
    """
    Menghitung metrik topologi jaringan untuk satu threshold.
    """
    n_nodes = G.number_of_nodes()
    n_edges = G.number_of_edges()

    density = nx.density(G) if n_nodes > 1 else 0

    degrees = dict(G.degree())
    avg_degree = np.mean(list(degrees.values())) if degrees else 0
    max_degree = max(degrees.values()) if degrees else 0
    min_degree = min(degrees.values()) if degrees else 0

    components = list(nx.connected_components(G))
    num_components = len(components)

    if components:
        giant_component = max(components, key=len)
        giant_component_size = len(giant_component)
        giant_component_ratio = giant_component_size / n_nodes
    else:
        giant_component_size = 0
        giant_component_ratio = 0

    isolated_nodes = list(nx.isolates(G))
    num_isolated_nodes = len(isolated_nodes)
    isolated_node_ratio = num_isolated_nodes / n_nodes if n_nodes > 0 else 0

    avg_clustering = nx.average_clustering(G) if n_edges > 0 else 0

    # Average shortest path hanya bisa dihitung jika graph connected.
    # Jika tidak connected, dihitung pada giant component.
    if giant_component_size > 1:
        G_giant = G.subgraph(giant_component).copy()
        avg_shortest_path = nx.average_shortest_path_length(G_giant)
        diameter = nx.diameter(G_giant)
    else:
        avg_shortest_path = 0
        diameter = 0

    # Modularity dihitung menggunakan greedy modularity communities
    if n_edges > 0:
        communities = list(nx.algorithms.community.greedy_modularity_communities(G))
        modularity_score = nx.algorithms.community.modularity(G, communities)
        num_communities = len(communities)
    else:
        modularity_score = 0
        num_communities = 0

    return {
        "threshold": threshold,
        "nodes": n_nodes,
        "edges": n_edges,
        "density": density,
        "avg_degree": avg_degree,
        "min_degree": min_degree,
        "max_degree": max_degree,
        "num_components": num_components,
        "giant_component_size": giant_component_size,
        "giant_component_ratio": giant_component_ratio,
        "num_isolated_nodes": num_isolated_nodes,
        "isolated_node_ratio": isolated_node_ratio,
        "avg_clustering": avg_clustering,
        "avg_shortest_path_giant": avg_shortest_path,
        "diameter_giant": diameter,
        "num_communities": num_communities,
        "modularity": modularity_score
    }


# ==== JALANKAN UJI SENSITIVITAS ====
results = []

for th in thresholds:
    print(f"Memproses threshold {th}...")

    G = build_network_from_similarity(sim_matrix, th)
    metrics = calculate_topology_metrics(G, th)
    results.append(metrics)

# Simpan hasil ke dataframe
sensitivity_df = pd.DataFrame(results)

# Simpan ke CSV
sensitivity_df.to_csv(output_sensitivity, index=False)

print("\n✅ Uji sensitivitas selesai!")
print(f"Hasil disimpan di: {output_sensitivity}")

# Tampilkan hasil
sensitivity_df

# ============================================================
# MENCARI THRESHOLD TERBAIK DARI FILE SIMILARITY DOID
# Berbasis sensitivitas topologi jaringan:
# - Giant component ratio
# - Isolated node ratio
# - Modularity
# - Density
# - Jumlah edge
# ============================================================

import os
import numpy as np
import pandas as pd
import networkx as nx
from networkx.algorithms.community import greedy_modularity_communities, modularity

# ------------------------------------------------------------
# 1. Path file
# ------------------------------------------------------------
similarity_file = "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/sclc_wangsimilarity_doid.csv"
output_sensitivity = "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/topologysclc_sensitivity_results.csv"

# Threshold yang akan diuji
thresholds = [0.30, 0.40, 0.50, 0.60, 0.70, 0.80]

# Bisa juga dibuat lebih halus:
# thresholds = np.round(np.arange(0.30, 0.81, 0.05), 2).tolist()


# ------------------------------------------------------------
# 2. Fungsi membaca file similarity
# ------------------------------------------------------------
def load_similarity_edges(path):
    df = pd.read_csv(path)

    sim_candidates = [
        c for c in df.columns
        if any(k in c.lower() for k in ["similarity", "sim", "score", "value"])
    ]

    if len(sim_candidates) > 0 and df.shape[1] >= 3:
        sim_col = sim_candidates[0]

        id_cols = [c for c in df.columns if c != sim_col]
        source_col = id_cols[0]
        target_col = id_cols[1]

        edges = df[[source_col, target_col, sim_col]].copy()
        edges.columns = ["source", "target", "similarity"]

    else:
        mat = pd.read_csv(path, index_col=0)
        mat = mat.apply(pd.to_numeric, errors="coerce")

        rows = []
        ids = mat.index.astype(str).tolist()

        for i in range(len(ids)):
            for j in range(i + 1, len(ids)):
                val = mat.iloc[i, j]
                if pd.notna(val):
                    rows.append([ids[i], ids[j], float(val)])

        edges = pd.DataFrame(rows, columns=["source", "target", "similarity"])

    edges["source"] = edges["source"].astype(str)
    edges["target"] = edges["target"].astype(str)
    edges["similarity"] = pd.to_numeric(edges["similarity"], errors="coerce")

    edges = edges.dropna(subset=["source", "target", "similarity"])
    edges = edges[edges["source"] != edges["target"]]

    edges["u"] = edges[["source", "target"]].min(axis=1)
    edges["v"] = edges[["source", "target"]].max(axis=1)

    edges = (
        edges.groupby(["u", "v"], as_index=False)["similarity"]
        .max()
        .rename(columns={"u": "source", "v": "target"})
    )

    return edges


# ------------------------------------------------------------
# 3. Fungsi min-max normalization
# ------------------------------------------------------------
def minmax(series):
    min_val = series.min()
    max_val = series.max()

    if max_val == min_val:
        return pd.Series([1.0] * len(series), index=series.index)

    return (series - min_val) / (max_val - min_val)


# ------------------------------------------------------------
# 4. Hitung sensitivitas topologi untuk setiap threshold
# ------------------------------------------------------------
edges = load_similarity_edges(similarity_file)

all_nodes = sorted(set(edges["source"]) | set(edges["target"]))
total_edges_available = len(edges)

results = []

for th in thresholds:
    selected_edges = edges[edges["similarity"] >= th].copy()

    G = nx.Graph()
    G.add_nodes_from(all_nodes)

    for _, row in selected_edges.iterrows():
        G.add_edge(
            row["source"],
            row["target"],
            weight=float(row["similarity"])
        )

    n_nodes = G.number_of_nodes()
    n_edges = G.number_of_edges()

    if n_nodes > 0:
        isolated_nodes = list(nx.isolates(G))
        num_isolated_nodes = len(isolated_nodes)
        isolated_node_ratio = num_isolated_nodes / n_nodes
    else:
        num_isolated_nodes = 0
        isolated_node_ratio = 0

    if n_edges > 0:
        components = list(nx.connected_components(G))
        num_components = len(components)
        giant_component_size = max(len(c) for c in components)
        giant_component_ratio = giant_component_size / n_nodes

        avg_degree = sum(dict(G.degree()).values()) / n_nodes
        density = nx.density(G)
        avg_edge_weight = selected_edges["similarity"].mean()
        edge_retention_ratio = n_edges / total_edges_available

        try:
            communities = list(greedy_modularity_communities(G, weight="weight"))
            if len(communities) > 1:
                mod = modularity(G, communities, weight="weight")
            else:
                mod = 0.0
            num_communities = len(communities)
        except Exception:
            mod = 0.0
            num_communities = 0

    else:
        num_components = n_nodes
        giant_component_size = 0
        giant_component_ratio = 0
        avg_degree = 0
        density = 0
        avg_edge_weight = 0
        edge_retention_ratio = 0
        mod = 0
        num_communities = 0

    results.append({
        "threshold": th,
        "num_nodes": n_nodes,
        "num_edges": n_edges,
        "edge_retention_ratio": edge_retention_ratio,
        "density": density,
        "avg_degree": avg_degree,
        "avg_edge_weight": avg_edge_weight,
        "num_components": num_components,
        "giant_component_size": giant_component_size,
        "giant_component_ratio": giant_component_ratio,
        "num_isolated_nodes": num_isolated_nodes,
        "isolated_node_ratio": isolated_node_ratio,
        "num_communities": num_communities,
        "modularity": mod
    })

sensitivity_df = pd.DataFrame(results)
sensitivity_df = sensitivity_df.sort_values("threshold").reset_index(drop=True)


# ------------------------------------------------------------
# 5. Skor gabungan topologi
# ------------------------------------------------------------
sensitivity_df["modularity_norm"] = minmax(sensitivity_df["modularity"])
sensitivity_df["giant_component_norm"] = minmax(sensitivity_df["giant_component_ratio"])
sensitivity_df["avg_edge_weight_norm"] = minmax(sensitivity_df["avg_edge_weight"])
sensitivity_df["isolated_node_inverse_norm"] = 1 - minmax(sensitivity_df["isolated_node_ratio"])

sensitivity_df["composite_score"] = (
    0.40 * sensitivity_df["modularity_norm"] +
    0.25 * sensitivity_df["giant_component_norm"] +
    0.20 * sensitivity_df["isolated_node_inverse_norm"] +
    0.15 * sensitivity_df["avg_edge_weight_norm"]
)


# ------------------------------------------------------------
# 6. Deteksi titik fragmentasi jaringan secara data-driven
# ------------------------------------------------------------
# GCR drop:
# positif jika giant_component_ratio turun dari threshold sebelumnya
sensitivity_df["gcr_drop"] = (
    sensitivity_df["giant_component_ratio"].shift(1) -
    sensitivity_df["giant_component_ratio"]
).fillna(0)

# Isolated jump:
# positif jika isolated_node_ratio naik dari threshold sebelumnya
sensitivity_df["isolated_jump"] = (
    sensitivity_df["isolated_node_ratio"] -
    sensitivity_df["isolated_node_ratio"].shift(1)
).fillna(0)

# Edge drop:
# positif jika jumlah edge turun tajam dari threshold sebelumnya
sensitivity_df["edge_drop_ratio"] = (
    sensitivity_df["num_edges"].shift(1) -
    sensitivity_df["num_edges"]
).fillna(0)

if sensitivity_df["num_edges"].max() > 0:
    sensitivity_df["edge_drop_ratio"] = (
        sensitivity_df["edge_drop_ratio"] / sensitivity_df["num_edges"].max()
    )
else:
    sensitivity_df["edge_drop_ratio"] = 0

# Hanya perubahan positif yang dianggap fragmentasi
sensitivity_df["gcr_drop_pos"] = sensitivity_df["gcr_drop"].clip(lower=0)
sensitivity_df["isolated_jump_pos"] = sensitivity_df["isolated_jump"].clip(lower=0)
sensitivity_df["edge_drop_pos"] = sensitivity_df["edge_drop_ratio"].clip(lower=0)

# Normalisasi perubahan agar sebanding
sensitivity_df["gcr_drop_norm"] = minmax(sensitivity_df["gcr_drop_pos"])
sensitivity_df["isolated_jump_norm"] = minmax(sensitivity_df["isolated_jump_pos"])
sensitivity_df["edge_drop_norm"] = minmax(sensitivity_df["edge_drop_pos"])

# Skor fragmentasi:
# semakin tinggi berarti jaringan makin mulai pecah
sensitivity_df["fragmentation_score"] = (
    0.45 * sensitivity_df["gcr_drop_norm"] +
    0.45 * sensitivity_df["isolated_jump_norm"] +
    0.10 * sensitivity_df["edge_drop_norm"]
)

# Abaikan baris threshold pertama karena tidak punya pembanding sebelumnya
fragmentation_candidates = sensitivity_df.iloc[1:].copy()

if fragmentation_candidates["fragmentation_score"].max() == 0:
    print("Tidak ditemukan penurunan GCR atau kenaikan isolated node yang tajam.")
    print("Threshold terbaik dipilih berdasarkan composite_score dari semua threshold.")
    fragmentation_threshold = None
    safe_df = sensitivity_df.copy()
else:
    frag_row = fragmentation_candidates.sort_values(
        "fragmentation_score",
        ascending=False
    ).iloc[0]

    fragmentation_threshold = frag_row["threshold"]

    # Threshold aman adalah threshold sebelum titik fragmentasi
    safe_df = sensitivity_df[
        sensitivity_df["threshold"] < fragmentation_threshold
    ].copy()

    # Jika kosong, gunakan semua threshold
    if safe_df.empty:
        safe_df = sensitivity_df.copy()


# ------------------------------------------------------------
# 7. Pilih threshold terbaik
# ------------------------------------------------------------
# Threshold terbaik dipilih dari area aman sebelum fragmentasi tajam
best_row = safe_df.sort_values(
    ["composite_score", "modularity", "giant_component_ratio"],
    ascending=False
).iloc[0]


# ------------------------------------------------------------
# 8. Simpan hasil
# ------------------------------------------------------------
os.makedirs(os.path.dirname(output_sensitivity), exist_ok=True)
sensitivity_df.to_csv(output_sensitivity, index=False)

print("=== HASIL SENSITIVITY THRESHOLD ===")
display(sensitivity_df)

print("\n=== DETEKSI TITIK FRAGMENTASI ===")
if fragmentation_threshold is None:
    print("Tidak ada titik fragmentasi tajam yang terdeteksi.")
else:
    print(f"Titik fragmentasi mulai terlihat pada threshold : {fragmentation_threshold}")
    print("Artinya, pada threshold tersebut jaringan mulai mengalami perubahan tajam.")
    print("Threshold kandidat dipilih dari nilai sebelum titik fragmentasi.")

print("\n=== THRESHOLD TERBAIK BERDASARKAN TOPOLOGI ===")
print(f"Best threshold        : {best_row['threshold']}")
print(f"Composite score       : {best_row['composite_score']:.4f}")
print(f"Modularity            : {best_row['modularity']:.4f}")
print(f"Giant component ratio : {best_row['giant_component_ratio']:.4f}")
print(f"Isolated node ratio   : {best_row['isolated_node_ratio']:.4f}")
print(f"Jumlah edge           : {int(best_row['num_edges'])}")
print(f"Jumlah komunitas      : {int(best_row['num_communities'])}")

print(f"\nFile hasil disimpan ke:\n{output_sensitivity}")

# ============================================
# GRAFIK GABUNGAN:
# GIANT COMPONENT RATIO, MODULARITY, & ISOLATED NODE RATIO
# ============================================

import matplotlib.pyplot as plt

plt.figure(figsize=(9, 5))

plt.plot(
    sensitivity_df["threshold"],
    sensitivity_df["giant_component_ratio"],
    marker="o",
    label="Giant Component Ratio"
)

plt.plot(
    sensitivity_df["threshold"],
    sensitivity_df["modularity"],
    marker="s",
    label="Modularity"
)

plt.plot(
    sensitivity_df["threshold"],
    sensitivity_df["isolated_node_ratio"],
    marker="^",
    linestyle="--",
    label="Isolated Node Ratio"
)

plt.xlabel("Threshold")
plt.ylabel("Value")
#plt.title("Perubahan Giant Component Ratio, Modularity, dan Isolated Node Ratio terhadap Threshold")
plt.ylim(0, 1.05)
plt.grid(True)
plt.legend()
plt.show()

# === 1. LOAD SIMILARITY MATRIX ===
# misal kamu sudah punya similarity_matrix dalam bentuk DataFrame
similarity_matrix = pd.read_csv('/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/sclc_wangsimilarity_doid.csv', index_col=0)

# ubah ke format edge list
similarity_df = similarity_matrix.stack().reset_index()
similarity_df.columns = ['source', 'target', 'weight']

# === 2. FILTER EDGES BERDASARKAN THRESHOLD ===
filtered_df = similarity_df[
    (similarity_df['weight'] >= 0.6) & (similarity_df['weight'] < 1)
]

# Simpan hasil edge list ke CSV
filtered_path = "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/filter_sclc.csv"
filtered_df.to_csv(filtered_path, index=False)

# === 3. BUAT NODE LIST ===
nodes = pd.unique(filtered_df[['source', 'target']].values.ravel())
nodes_df = pd.DataFrame({'id': nodes})
nodes_path = "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/nodes_sclc.csv"
nodes_df.to_csv(nodes_path, index=False)

print(f"✅ Selesai! Hasil disimpan di: {filtered_path}")

# === 1. BACA FILE MAPPING TXT ===
mapping_path = "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/3_pubtator_ids_cleaned.txt"
filter_path = "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/filter_sclc.csv"
output_path = "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/filter_diseasesclc.csv"

# Parsing baris satu per satu
mapping = {}
with open(mapping_path, 'r', encoding='utf-8') as f:
    for line in f:
        line = line.strip()
        if not line:
            continue
        match = re.match(r'(.+?):\s*DOID[_:](\d+)', line)
        if match:
            disease_name = match.group(1).strip()
            doid = f"DOID:{match.group(2)}"
            mapping[doid] = disease_name

# Cek hasil parsing sebagian
print(f"Total mapping ditemukan: {len(mapping)}")
print(list(mapping.items())[:5])  # contoh hasil

# === 2. BACA FILE FILTER ===
filter_df = pd.read_csv(filter_path)

# === 3. GANTI DOID DENGAN NAMA PENYAKIT ===
def map_doid_to_name(doid):
    return mapping.get(doid, doid)  # kalau tidak ditemukan, tetap DOID

filter_df['source'] = filter_df['source'].map(map_doid_to_name)
filter_df['target'] = filter_df['target'].map(map_doid_to_name)

# === 4. SIMPAN SEBAGAI FILE BARU ===
filter_df.to_csv(output_path, index=False, encoding='utf-8')

print(f"✅ File berhasil dibuat: {output_path}")

# baca file asli
df = pd.read_csv("/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/filter_diseasesclc.csv")

# bikin dataframe baru sesuai spesifikasi
new_df = pd.DataFrame({
    "txt": df["source"],
    "txt.1": df["target"],
    "num": 1,
    "num.1": 1,
    "num.2": df["weight"]
})

# simpan file baru
new_df.to_csv("/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/sclc_disease_pub.csv", index=False)

print("Selesai. File disimpan sebagai sclc_disease_pub.csv")

import matplotlib.pyplot as plt
import networkx as nx

def load_disease_csv(path):
    df = pd.read_csv(path)

    required = ["txt", "txt.1", "num", "num.1", "num.2"]
    for c in required:
        if c not in df.columns:
            raise ValueError(f"Kolom '{c}' hilang dari CSV kamu.")

    G = nx.Graph()

    for _, row in df.iterrows():
        src = str(row["txt"])
        dst = str(row["txt.1"])
        weight = float(row["num.2"]) if not pd.isna(row["num.2"]) else 1.0
        G.add_edge(src, dst, weight=weight)

    return G


def plot_graph(G):
    plt.figure(figsize=(20, 14))

    pos = nx.spring_layout(G, seed=42)

    # Draw nodes
    nx.draw_networkx_nodes(G, pos, node_size=500, node_color="skyblue")

    # Draw edges
    nx.draw_networkx_edges(G, pos, width=1.0, alpha=0.7)

    # Draw labels
    nx.draw_networkx_labels(G, pos, font_size=8)

    plt.title("Comorbidities SCLC")
    plt.axis("off")
    plt.show()


# Pemakaian
file_path = "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc/sclc_disease_pub.csv"
G = load_disease_csv(file_path)

print("Nodes:", G.number_of_nodes())
print("Edges:", G.number_of_edges())

plot_graph(G)

# Ambil semua komponen dulu sebagai list
komponen = list(nx.connected_components(G))

# Urutkan berdasarkan ukuran
komponen_sorted = sorted(komponen, key=len, reverse=True)

# Tampilkan info komponen
nkomponen = [len(c) for c in komponen_sorted]
print("banyaknya komponen pada network :", len(nkomponen))
print("yaitu :", nkomponen)