# -*- coding: utf-8 -*-
"""Overlapping Nodes SCLC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1anjUIvIC7T0WT6GxywzbMuGMOKHFbzgf
"""

!pip install venn

from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

import json
from pathlib import Path

dataset = "sclc"   # atau "nsclc"

best_dir = Path("/content/gdrive/MyDrive/dataset/Tesis/pubtator/BestRun")

summary_file = best_dir / f"{dataset}_best_run_summary.json"
membership_file = best_dir / f"{dataset}_best_memberships.json"

print("Folder ada?", best_dir.exists())
print("Summary ada?", summary_file.exists())
print("Membership ada?", membership_file.exists())

print("\nIsi folder:")
for item in best_dir.iterdir():
    print("-", item.name)

# =========================
# 2. LOAD BEST RUN SUMMARY
# =========================

with open(summary_file, "r") as f:
    best_summary = json.load(f)

print("=== BEST RUN SUMMARY ===")
print(json.dumps(best_summary, indent=2))


# =========================
# 3. LOAD BEST MEMBERSHIP
# =========================

with open(membership_file, "r") as f:
    raw_membership = json.load(f)

print("\nTipe data membership:", type(raw_membership))

if isinstance(raw_membership, dict):
    print("Jumlah key:", len(raw_membership))
    first_key = list(raw_membership.keys())[0]
    print("Contoh key pertama:", first_key)
    print("Contoh value:", raw_membership[first_key])
elif isinstance(raw_membership, list):
    print("Jumlah baris:", len(raw_membership))
    print("Contoh baris:", raw_membership[0])

def normalize_membership(raw_membership):
    """
    Mengubah berbagai kemungkinan format membership menjadi:

    {
        node_id: {
            community_id: membership_value,
            ...
        },
        ...
    }
    """

    # Format 1:
    # {
    #   "48": {"2": 0.92, "16": 0.08},
    #   ...
    # }
    if isinstance(raw_membership, dict):
        # Kalau ada wrapper seperti "best_memberships" atau "fuzzy_membership"
        possible_keys = [
            "best_memberships",
            "fuzzy_membership",
            "memberships",
            "membership",
            "node_memberships"
        ]

        for key in possible_keys:
            if key in raw_membership:
                raw_membership = raw_membership[key]
                break

        normalized = {}

        for node, membership_dict in raw_membership.items():

            if isinstance(membership_dict, str):
                membership_dict = ast.literal_eval(membership_dict)

            normalized[str(node)] = {
                str(comm): float(mu)
                for comm, mu in membership_dict.items()
            }

        return normalized

    # Format 2:
    # [
    #   {"node": 48, "community": 2, "membership": 0.92},
    #   {"node": 48, "community": 16, "membership": 0.08}
    # ]
    elif isinstance(raw_membership, list):
        normalized = {}

        for row in raw_membership:
            node = str(row.get("node", row.get("node_id")))
            comm = str(row.get("community", row.get("community_id", row.get("comm"))))
            mu = float(row.get("membership", row.get("mu", row.get("value"))))

            if node not in normalized:
                normalized[node] = {}

            normalized[node][comm] = mu

        return normalized

    else:
        raise ValueError("Format membership tidak dikenali.")


fuzzy_membership = normalize_membership(raw_membership)

print("Jumlah node dalam best membership:", len(fuzzy_membership))

# tampilkan contoh 5 node
for i, (node, memb) in enumerate(fuzzy_membership.items()):
    print(node, memb)
    if i == 4:
        break

def detect_overlapping_nodes(fuzzy_membership, alpha_threshold):
    """
    Node disebut overlapping jika memiliki minimal dua komunitas
    dengan nilai membership >= alpha_threshold.
    """

    rows = []

    for node, membership_dict in fuzzy_membership.items():

        memberships = {
            str(comm): float(mu)
            for comm, mu in membership_dict.items()
        }

        selected = {
            comm: mu
            for comm, mu in memberships.items()
            if mu >= alpha_threshold
        }

        sorted_memberships = sorted(
            memberships.items(),
            key=lambda x: x[1],
            reverse=True
        )

        top1_comm, top1_mu = sorted_memberships[0]

        if len(sorted_memberships) > 1:
            top2_comm, top2_mu = sorted_memberships[1]
        else:
            top2_comm, top2_mu = None, 0.0

        if len(selected) >= 2:
            rows.append({
                "node": node,
                "alpha_threshold": alpha_threshold,
                "num_selected_communities": len(selected),
                "selected_communities": list(selected.keys()),
                "selected_memberships": selected,
                "top1_community": top1_comm,
                "top1_membership": top1_mu,
                "top2_community": top2_comm,
                "top2_membership": top2_mu,
                "membership_gap_top1_top2": top1_mu - top2_mu,
                "all_memberships": memberships
            })

    return pd.DataFrame(rows)

out_dir = Path("/content/gdrive/MyDrive/dataset/Tesis/pubtator/BestRun/sclc_threshold_sensitivity")
sensitivity_rows = []
detail_all = []

total_nodes = len(fuzzy_membership)

for alpha in thresholds:
    df_overlap = detect_overlapping_nodes(
        fuzzy_membership=fuzzy_membership,
        alpha_threshold=alpha
    )

    num_overlap = len(df_overlap)
    overlap_ratio = num_overlap / total_nodes if total_nodes > 0 else 0

    overlapping_nodes = df_overlap["node"].tolist() if num_overlap > 0 else []

    sensitivity_rows.append({
        "alpha_threshold": alpha,
        "total_nodes": total_nodes,
        "num_overlapping_nodes": num_overlap,
        "overlapping_node_ratio": overlap_ratio,
        "overlapping_nodes": overlapping_nodes
    })

    # simpan detail per threshold
    df_overlap.to_csv(
        os.path.join(out_dir, f"{prefix}_overlapping_nodes_alpha_{alpha:.2f}.csv"),
        index=False
    )

    if num_overlap > 0:
        detail_all.append(df_overlap)

sensitivity_df = pd.DataFrame(sensitivity_rows)

if detail_all:
    detail_df = pd.concat(detail_all, ignore_index=True)
else:
    detail_df = pd.DataFrame()

# simpan hasil utama
sensitivity_df.to_csv(
    os.path.join(out_dir, f"{prefix}_overlapping_threshold_sensitivity_best_run.csv"),
    index=False
)

detail_df.to_csv(
    os.path.join(out_dir, f"{prefix}_overlapping_detail_all_thresholds_best_run.csv"),
    index=False
)

print("=== HASIL SENSITIVITAS THRESHOLD ===")
display(sensitivity_df)

print("=== DETAIL NODE OVERLAPPING ===")
display(detail_df)

plt.figure(figsize=(7, 5))

plt.plot(
    sensitivity_df["alpha_threshold"],
    sensitivity_df["num_overlapping_nodes"],
    marker="o"
)

plt.xlabel("Alpha Threshold")
plt.ylabel("Number of Overlapping Nodes")
plt.title(f"Sensitivity of Overlapping Nodes on {prefix.upper()} Best Run")
plt.grid(True)
plt.show()

import pandas as pd
import ast
import matplotlib.pyplot as plt

# ==========================================
# LOAD FILE RINGKASAN SENSITIVITAS
# ==========================================
base_dir = "/content/gdrive/MyDrive/dataset/Tesis/pubtator/BestRun/sclc_threshold_sensitivity"
prefix = "sclc"

summary_path = f"{base_dir}/{prefix}_overlapping_threshold_sensitivity_best_run.csv"
sensitivity_df = pd.read_csv(summary_path)

display(sensitivity_df)

def to_set(x):
    if pd.isna(x) or str(x).strip() == "":
        return set()
    if isinstance(x, list):
        return set(x)
    return set(ast.literal_eval(x))

venn_sets = {}

for _, row in sensitivity_df.iterrows():
    alpha = row["alpha_threshold"]
    label = f"α={alpha:.2f}"
    venn_sets[label] = to_set(row["overlapping_nodes"])

print(venn_sets)

from venn import venn

plt.figure(figsize=(10, 10))
venn(venn_sets)
plt.title("Venn Diagram Node Overlapping pada Berbagai Alpha Threshold")
plt.show()

from itertools import combinations
import pandas as pd

# pastikan label sesuai dengan yang ada di venn_sets
labels = ["α=0.30", "α=0.35", "α=0.40", "α=0.45", "α=0.50"]

region_rows = []

for r in range(1, len(labels) + 1):
    for combo in combinations(labels, r):

        # node yang ada di semua set dalam combo
        included = set.intersection(*(venn_sets[label] for label in combo))

        # node yang tidak boleh ada di set lain di luar combo
        excluded_labels = [label for label in labels if label not in combo]

        if excluded_labels:
            excluded = set.union(*(venn_sets[label] for label in excluded_labels))
            region_nodes = included - excluded
        else:
            region_nodes = included

        if len(region_nodes) > 0:
            region_rows.append({
                "region": " ∩ ".join(combo),
                "num_nodes": len(region_nodes),
                "nodes": sorted(region_nodes)
            })

region_df = pd.DataFrame(region_rows)

display(region_df)

region_df.to_csv(
    f"{base_dir}/{prefix}_venn_region_nodes.csv",
    index=False
)

import ast
import pandas as pd

def parse_node_list(x):
    if isinstance(x, list):
        return x
    if isinstance(x, set):
        return list(x)

    s = str(x).strip()

    try:
        val = ast.literal_eval(s)
        if isinstance(val, list):
            return val
    except:
        pass

    return [i.strip() for i in s.split(",") if i.strip()]

# ambil baris keempat / index 3
stable_nodes = parse_node_list(region_df.loc[4, "nodes"])

print("Node overlapping paling stabil:")
for n in stable_nodes:
    print("-", n)

alpha_plot = 0.5

# supaya aman kalau huruf besar/kecil berbeda
node_lookup = {
    str(node).strip().lower(): node
    for node in fuzzy_membership.keys()
}

rows = []

for node_name in stable_nodes:
    node_key = node_lookup.get(node_name.lower())

    if node_key is None:
        print(f"Node tidak ditemukan di fuzzy_membership: {node_name}")
        continue

    memberships = {
        str(comm): float(mu)
        for comm, mu in fuzzy_membership[node_key].items()
    }

    selected = {
        comm: mu
        for comm, mu in memberships.items()
        if mu >= alpha_plot
    }

    sorted_selected = sorted(
        selected.items(),
        key=lambda x: x[1],
        reverse=True
    )

    sorted_all = sorted(
        memberships.items(),
        key=lambda x: x[1],
        reverse=True
    )

    rows.append({
        "node": node_name,
        "alpha_threshold": alpha_plot,
        "overlapping_communities": [comm for comm, mu in sorted_selected],
        "membership_values": {comm: round(mu, 4) for comm, mu in sorted_selected},
        "num_overlapping_communities": len(sorted_selected),
        "dominant_community": sorted_all[0][0],
        "dominant_membership": round(sorted_all[0][1], 4),
        "second_community": sorted_all[1][0] if len(sorted_all) > 1 else None,
        "second_membership": round(sorted_all[1][1], 4) if len(sorted_all) > 1 else None,
        "membership_gap": round(sorted_all[0][1] - sorted_all[1][1], 4) if len(sorted_all) > 1 else None,
        "all_memberships": {comm: round(mu, 4) for comm, mu in sorted_all}
    })

stable_overlap_df = pd.DataFrame(rows)

display(stable_overlap_df)

stable_overlap_df.to_csv(
    f"{out_dir}/{prefix}_stable_overlapping_nodes_communities_alpha_05.csv",
    index=False
)

import pandas as pd
import ast
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import math
import textwrap

# kalau stable_overlap_df hasil load dari csv
stable_overlap_df = pd.read_csv(f"{out_dir}/{prefix}_stable_overlapping_nodes_communities_alpha_05.csv")

plot_source_df = stable_overlap_df.copy()

# karena kolom kamu namanya "node", ubah jadi "overlapping_node"
if "overlapping_node" not in plot_source_df.columns:
    if "node" in plot_source_df.columns:
        plot_source_df = plot_source_df.rename(columns={"node": "overlapping_node"})
    else:
        raise ValueError("Kolom node / overlapping_node tidak ditemukan.")

display(plot_source_df.head())

def normalize_comm_id(x):
    try:
        return str(int(float(x)))
    except:
        return str(x)

def parse_list_or_dict(x):
    if isinstance(x, (list, dict)):
        return x
    return ast.literal_eval(str(x))

stable_nodes = parse_node_list(region_df.loc[4, "nodes"])

plot_rows = []

for _, row in plot_source_df.iterrows():
    overlap_node = row["overlapping_node"]

    if overlap_node not in stable_nodes:
        continue

    overlapping_communities = parse_list_or_dict(row["overlapping_communities"])
    membership_values = parse_list_or_dict(row["membership_values"])

    for comm in overlapping_communities:
        comm_id = normalize_comm_id(comm)

        plot_rows.append({
            "overlapping_node": overlap_node,
            "internal_community_label": comm_id,
            "membership_value": membership_values.get(comm_id, membership_values.get(comm, None))
        })

plot_df = pd.DataFrame(plot_rows)

display(plot_df)

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

graph_path = "/content/gdrive/MyDrive/dataset/Tesis/pubtator/sclc/sclc_disease_pub.csv"

df_edge = pd.read_csv(graph_path)

print(df_edge.head())
print(df_edge.columns)

def load_graph_from_csv(df):
    possible_pairs = [
        ("source", "target"),
        ("Source", "Target"),
        ("node1", "node2"),
        ("disease1", "disease2"),
        ("disease_a", "disease_b"),
        ("from", "to"),
        ("u", "v")
    ]

    source_col, target_col = None, None

    for a, b in possible_pairs:
        if a in df.columns and b in df.columns:
            source_col, target_col = a, b
            break

    if source_col is None:
        source_col, target_col = df.columns[0], df.columns[1]

    weight_col = None
    for col in ["weight", "similarity", "score", "wang_similarity"]:
        if col in df.columns:
            weight_col = col
            break

    G = nx.Graph()

    for _, row in df.iterrows():
        u = str(row[source_col]).strip()
        v = str(row[target_col]).strip()

        if weight_col is not None:
            w = float(row[weight_col])
        else:
            w = 1.0

        G.add_edge(u, v, weight=w)

    return G

G = load_graph_from_csv(df_edge)

print("Jumlah node:", G.number_of_nodes())
print("Jumlah edge:", G.number_of_edges())

stable_nodes_actual = []

graph_node_lookup = {
    str(node).strip().lower(): node
    for node in G.nodes()
}

for node in stable_nodes:
    key = graph_node_lookup.get(node.lower())
    if key is not None:
        stable_nodes_actual.append(key)
    else:
        print("Tidak ditemukan di graph:", node)

plot_nodes = set(stable_nodes_actual)

for node in stable_nodes_actual:
    plot_nodes.update(G.neighbors(node))

subG = G.subgraph(plot_nodes).copy()

print("Jumlah node pada subnetwork:", subG.number_of_nodes())
print("Jumlah edge pada subnetwork:", subG.number_of_edges())

alpha_member = 0.50

def norm_text(x):
    return str(x).strip().lower()


def get_members_of_internal_community(comm_id, fuzzy_membership, alpha_member=0.30):
    members = []

    comm_id = normalize_comm_id(comm_id)

    for node, memb in fuzzy_membership.items():
        memb_norm = {
            normalize_comm_id(k): float(v)
            for k, v in memb.items()
        }

        if comm_id in memb_norm and memb_norm[comm_id] >= alpha_member:
            members.append((str(node), memb_norm[comm_id]))

    members = sorted(members, key=lambda x: x[1], reverse=True)
    return members


def choose_representative_disease_unique(
    comm_id,
    overlap_node,
    fuzzy_membership,
    G,
    stable_nodes,
    used_representatives,
    representative_cache,
    alpha_member=0.30
):
    comm_id = normalize_comm_id(comm_id)

    if comm_id in representative_cache:
        return representative_cache[comm_id]

    members = get_members_of_internal_community(
        comm_id=comm_id,
        fuzzy_membership=fuzzy_membership,
        alpha_member=alpha_member
    )

    stable_lc = {norm_text(s) for s in stable_nodes}
    used_lc = {norm_text(u) for u in used_representatives}
    overlap_lc = norm_text(overlap_node)

    # daftar label generik yang tidak boleh dijadikan representative
    banned_labels = {
        "cancer",
        "tumor",
        "neoplasm",
        "malignant neoplasm",
        "carcinoma"
    }

    graph_lookup = {
        norm_text(n): n
        for n in G.nodes()
    }

    candidates = []

    for node, mu in members:
        node_lc = norm_text(node)

        # skip stable overlapping nodes
        if node_lc in stable_lc:
            continue

        # skip overlap node itu sendiri
        if node_lc == overlap_lc:
            continue

        # skip representative yang sudah dipakai
        if node_lc in used_lc:
            continue

        # skip label terlalu umum
        if node_lc in banned_labels:
            continue

        if node_lc in graph_lookup:
            actual_node = graph_lookup[node_lc]
            degree = G.degree(actual_node)
        else:
            actual_node = node
            degree = 0

        candidates.append({
            "node": str(actual_node),
            "membership": mu,
            "degree": degree
        })

    if len(candidates) > 0:
        candidates = sorted(
            candidates,
            key=lambda x: (x["degree"], x["membership"]),
            reverse=True
        )

        chosen = candidates[0]["node"]
        used_representatives.add(chosen)
        representative_cache[comm_id] = chosen
        return chosen

    # fallback kalau semua kandidat terfilter
    fallback_label = f"Community {comm_id}"
    representative_cache[comm_id] = fallback_label
    return fallback_label

import re
import numpy as np
import pandas as pd
import networkx as nx

# =====================================================
# 1. FILTER NODE YANG BUKAN PENYAKIT VALID
# =====================================================

def is_invalid_representative_node(x):
    """
    True jika node hanya label komunitas, bukan disease node.
    Contoh yang dibuang:
    - Community 3937
    - community 4425
    - C3937
    - C_3937
    """
    x = str(x).strip().lower()

    patterns = [
        r"^community\s*\d+$",
        r"^community\s*_\s*\d+$",
        r"^c\s*\d+$",
        r"^c_\s*\d+$"
    ]

    return any(re.match(p, x) for p in patterns)


def normalize_comm_key(x):
    """
    Menyamakan label community:
    3937, '3937', 'C3937' -> '3937'
    """
    x = str(x).strip()
    x = re.sub(r"^C", "", x, flags=re.IGNORECASE)
    return x


def get_membership_value(fuzzy_membership, node, comm_id):
    """
    Mengambil membership value secara fleksibel.
    Mendukung struktur:
    1. fuzzy_membership[node][comm_id]
    2. fuzzy_membership[comm_id][node]
    """

    comm_key = normalize_comm_key(comm_id)

    # Case 1: fuzzy_membership[node][comm]
    if isinstance(fuzzy_membership, dict) and node in fuzzy_membership:
        val = fuzzy_membership[node]

        if isinstance(val, dict):
            possible_keys = [
                comm_id,
                str(comm_id),
                comm_key,
                f"C{comm_key}"
            ]

            for k in possible_keys:
                if k in val:
                    return float(val[k])

        elif isinstance(val, list):
            try:
                idx = int(comm_key)
                if 0 <= idx < len(val):
                    return float(val[idx])
            except:
                pass

    # Case 2: fuzzy_membership[comm][node]
    if isinstance(fuzzy_membership, dict):
        possible_comm_keys = [
            comm_id,
            str(comm_id),
            comm_key,
            f"C{comm_key}"
        ]

        for ck in possible_comm_keys:
            if ck in fuzzy_membership:
                val = fuzzy_membership[ck]

                if isinstance(val, dict) and node in val:
                    return float(val[node])

    return 0.0


# =====================================================
# 2. FUNGSI PEMILIH REPRESENTATIVE DISEASE YANG BARU
# =====================================================

def choose_representative_disease_unique_v2(
    comm_id,
    overlap_node,
    fuzzy_membership,
    G,
    stable_nodes,
    used_representatives,
    representative_cache=None,
    alpha_member=0.40,
    allow_relax_threshold=True
):
    """
    Memilih representative disease valid untuk suatu community.

    Prioritas:
    1. Node penyakit valid dengan membership >= alpha_member pada community tersebut.
    2. Jika tidak ada, threshold dilonggarkan menjadi membership > 0.
    3. Jika masih tidak ada, gunakan tetangga overlap_node yang valid.
    4. Jika masih tidak ada, return None.

    Skor pemilihan:
    - membership value
    - degree node dalam G
    - edge weight terhadap overlap_node jika ada
    """

    stable_nodes_set = set(stable_nodes)

    # Jangan langsung pakai cache jika isinya invalid atau sudah digunakan
    cache_key = normalize_comm_key(comm_id)

    if representative_cache is not None and cache_key in representative_cache:
        cached = representative_cache[cache_key]

        if (
            cached is not None
            and not is_invalid_representative_node(cached)
            and cached not in stable_nodes_set
            and cached not in used_representatives
            and cached != overlap_node
            and cached in G.nodes()
        ):
            used_representatives.add(cached)
            return cached

    candidates = []

    # -------------------------------------------------
    # A. Kandidat utama: semua node dalam graph
    # -------------------------------------------------
    for node in G.nodes():

        if node == overlap_node:
            continue

        if node in stable_nodes_set:
            continue

        if node in used_representatives:
            continue

        if is_invalid_representative_node(node):
            continue

        membership = get_membership_value(
            fuzzy_membership=fuzzy_membership,
            node=node,
            comm_id=comm_id
        )

        if membership >= alpha_member:
            degree = G.degree(node)

            edge_weight = 0.0
            if G.has_edge(overlap_node, node):
                edge_weight = G[overlap_node][node].get("weight", 1.0)

            candidates.append({
                "node": node,
                "membership": membership,
                "degree": degree,
                "edge_weight": edge_weight,
                "source": "membership>=alpha"
            })

    # -------------------------------------------------
    # B. Jika tidak ada, longgarkan threshold membership
    # -------------------------------------------------
    if len(candidates) == 0 and allow_relax_threshold:

        for node in G.nodes():

            if node == overlap_node:
                continue

            if node in stable_nodes_set:
                continue

            if node in used_representatives:
                continue

            if is_invalid_representative_node(node):
                continue

            membership = get_membership_value(
                fuzzy_membership=fuzzy_membership,
                node=node,
                comm_id=comm_id
            )

            if membership > 0:
                degree = G.degree(node)

                edge_weight = 0.0
                if G.has_edge(overlap_node, node):
                    edge_weight = G[overlap_node][node].get("weight", 1.0)

                candidates.append({
                    "node": node,
                    "membership": membership,
                    "degree": degree,
                    "edge_weight": edge_weight,
                    "source": "membership>0"
                })

    # -------------------------------------------------
    # C. Jika tetap tidak ada, pakai tetangga overlap_node
    # -------------------------------------------------
    if len(candidates) == 0 and overlap_node in G.nodes():

        for node in G.neighbors(overlap_node):

            if node == overlap_node:
                continue

            if node in stable_nodes_set:
                continue

            if node in used_representatives:
                continue

            if is_invalid_representative_node(node):
                continue

            membership = get_membership_value(
                fuzzy_membership=fuzzy_membership,
                node=node,
                comm_id=comm_id
            )

            degree = G.degree(node)
            edge_weight = G[overlap_node][node].get("weight", 1.0)

            candidates.append({
                "node": node,
                "membership": membership,
                "degree": degree,
                "edge_weight": edge_weight,
                "source": "neighbor_fallback"
            })

    if len(candidates) == 0:
        return None

    candidate_df = pd.DataFrame(candidates)

    # Urutan prioritas:
    # membership terbesar, degree terbesar, edge weight terbesar
    candidate_df = candidate_df.sort_values(
        by=["membership", "degree", "edge_weight"],
        ascending=[False, False, False]
    ).reset_index(drop=True)

    selected = candidate_df.loc[0, "node"]

    used_representatives.add(selected)

    if representative_cache is not None:
        representative_cache[cache_key] = selected

    return selected

import re
import numpy as np
import pandas as pd
import networkx as nx

# =====================================================
# 1. FILTER NODE NON-DISEASE
# =====================================================

def is_invalid_representative_node(x):
    """
    True jika node bukan nama penyakit valid.
    Contoh yang dibuang:
    - Community 3937
    - C3937
    - C_3937
    """
    x = str(x).strip().lower()

    patterns = [
        r"^community\s*\d+$",
        r"^community\s*_\s*\d+$",
        r"^c\s*\d+$",
        r"^c_\s*\d+$"
    ]

    return any(re.match(p, x) for p in patterns)


def is_valid_disease_node(x):
    x = str(x).strip()

    if x == "":
        return False

    if is_invalid_representative_node(x):
        return False

    return True


def normalize_comm_key(x):
    """
    3937, '3937', 'C3937' -> '3937'
    """
    x = str(x).strip()
    x = re.sub(r"^C", "", x, flags=re.IGNORECASE)
    return x


# =====================================================
# 2. FUNGSI AMBIL MEMBERSHIP
# =====================================================

def get_membership_value(fuzzy_membership, node, comm_id):
    """
    Mendukung beberapa kemungkinan format fuzzy_membership:
    1. fuzzy_membership[node][community]
    2. fuzzy_membership[community][node]
    """

    comm_key = normalize_comm_key(comm_id)
    possible_comm_keys = [
        comm_id,
        str(comm_id),
        comm_key,
        f"C{comm_key}",
        f"Community {comm_key}"
    ]

    # Format: fuzzy_membership[node][community]
    if isinstance(fuzzy_membership, dict) and node in fuzzy_membership:
        val = fuzzy_membership[node]

        if isinstance(val, dict):
            for k in possible_comm_keys:
                if k in val:
                    return float(val[k])

        elif isinstance(val, list):
            try:
                idx = int(comm_key)
                if 0 <= idx < len(val):
                    return float(val[idx])
            except:
                pass

    # Format: fuzzy_membership[community][node]
    if isinstance(fuzzy_membership, dict):
        for ck in possible_comm_keys:
            if ck in fuzzy_membership:
                val = fuzzy_membership[ck]

                if isinstance(val, dict) and node in val:
                    return float(val[node])

    return 0.0


# =====================================================
# 3. SKOR KANDIDAT REPRESENTATIVE DISEASE
# =====================================================

def normalize_series(x):
    x = pd.Series(x, dtype=float)

    if x.max() == x.min():
        return pd.Series(np.ones(len(x)), index=x.index)

    return (x - x.min()) / (x.max() - x.min())


def choose_representative_disease_robust(
    comm_id,
    overlap_node,
    fuzzy_membership,
    G,
    stable_nodes,
    used_representatives=None,
    alpha_member=0.40,
    allow_reuse_as_fallback=True
):
    """
    Memilih representative disease dengan fallback bertingkat.

    Prioritas:
    1. Disease valid dengan membership >= alpha_member.
    2. Disease valid dengan membership > 0.
    3. Tetangga valid dari overlap_node.
    4. Semua disease valid dalam graph.

    Skor:
    - membership value
    - degree
    - edge weight terhadap overlap node
    """

    if used_representatives is None:
        used_representatives = set()

    stable_nodes_set = set(stable_nodes)

    def collect_candidates(mode, exclude_used=True):
        candidates = []

        if mode in ["membership_alpha", "membership_positive", "all_graph"]:
            node_pool = list(G.nodes())

        elif mode == "neighbor":
            if overlap_node not in G.nodes():
                return []
            node_pool = list(G.neighbors(overlap_node))

        else:
            node_pool = []

        for node in node_pool:

            if node == overlap_node:
                continue

            if node in stable_nodes_set:
                continue

            if exclude_used and node in used_representatives:
                continue

            if not is_valid_disease_node(node):
                continue

            membership = get_membership_value(
                fuzzy_membership=fuzzy_membership,
                node=node,
                comm_id=comm_id
            )

            if mode == "membership_alpha" and membership < alpha_member:
                continue

            if mode == "membership_positive" and membership <= 0:
                continue

            degree = G.degree(node)

            edge_weight = 0.0
            if G.has_edge(overlap_node, node):
                edge_weight = G[overlap_node][node].get("weight", 1.0)

            candidates.append({
                "node": node,
                "membership": membership,
                "degree": degree,
                "edge_weight": edge_weight,
                "source": mode
            })

        return candidates

    # Urutan pencarian kandidat
    search_modes = [
        "membership_alpha",
        "membership_positive",
        "neighbor",
        "all_graph"
    ]

    candidates = []

    # Pertama: cari kandidat yang belum pernah dipakai
    for mode in search_modes:
        candidates = collect_candidates(mode, exclude_used=True)
        if len(candidates) > 0:
            break

    # Kedua: kalau tidak ada, izinkan reuse agar node tetap punya representative
    if len(candidates) == 0 and allow_reuse_as_fallback:
        for mode in search_modes:
            candidates = collect_candidates(mode, exclude_used=False)
            if len(candidates) > 0:
                break

    if len(candidates) == 0:
        return None, None

    cand_df = pd.DataFrame(candidates)

    cand_df["membership_norm"] = normalize_series(cand_df["membership"])
    cand_df["degree_norm"] = normalize_series(cand_df["degree"])
    cand_df["edge_weight_norm"] = normalize_series(cand_df["edge_weight"])

    cand_df["score"] = (
        0.50 * cand_df["membership_norm"] +
        0.30 * cand_df["degree_norm"] +
        0.20 * cand_df["edge_weight_norm"]
    )

    cand_df = cand_df.sort_values(
        by=["score", "membership", "degree", "edge_weight"],
        ascending=[False, False, False, False]
    ).reset_index(drop=True)

    selected = cand_df.loc[0, "node"]
    source = cand_df.loc[0, "source"]

    used_representatives.add(selected)

    return selected, source


# =====================================================
# 4. BENTUK GRAPH H DAN COMMUNITY_INFO_DF
# =====================================================

H = nx.Graph()

stable_nodes = list(stable_nodes)

for node in stable_nodes:
    H.add_node(
        node,
        kind="overlap",
        label=node
    )

community_info = []
used_representatives = set()

missing_rows = []

for _, row in plot_df.iterrows():

    overlap_node = row["overlapping_node"]
    comm_id = row["internal_community_label"]
    membership_value = row["membership_value"]

    rep_disease, selection_source = choose_representative_disease_robust(
        comm_id=comm_id,
        overlap_node=overlap_node,
        fuzzy_membership=fuzzy_membership,
        G=subG,
        stable_nodes=stable_nodes,
        used_representatives=used_representatives,
        alpha_member=0.40,
        allow_reuse_as_fallback=True
    )

    if rep_disease is None:
        missing_rows.append({
            "overlap_node": overlap_node,
            "community": comm_id,
            "membership_value": membership_value
        })
        continue

    comm_label = str(comm_id)

    if not comm_label.startswith("C"):
        comm_label = f"C{comm_label}"

    rep_node_id = f"{comm_label}__{rep_disease}"

    H.add_node(
        rep_node_id,
        kind="representative",
        label=rep_disease,
        community=comm_id
    )

    H.add_edge(
        overlap_node,
        rep_node_id,
        weight=membership_value
    )

    community_info.append({
        "overlap_node": overlap_node,
        "community": comm_id,
        "rep_node_id": rep_node_id,
        "rep_disease": rep_disease,
        "membership_value": membership_value,
        "selection_source": selection_source
    })

community_info_df = pd.DataFrame(community_info)
missing_rep_df = pd.DataFrame(missing_rows)

print("Jumlah baris plot_df:", len(plot_df))
print("Jumlah representative disease valid:", len(community_info_df))
print("Jumlah yang tetap tidak punya representative:", len(missing_rep_df))

display(community_info_df)

if len(missing_rep_df) > 0:
    print("Baris yang tetap tidak punya representative:")
    display(missing_rep_df)

import os
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
import textwrap

# =====================================================
# VISUALISASI STABLE OVERLAPPING NODES
# DAN REPRESENTATIVE DISEASES DARI KOMUNITAS TERHUBUNG
# =====================================================

# Pastikan output folder tersedia
os.makedirs(out_dir, exist_ok=True)

# Pastikan stable_nodes berupa list
stable_nodes = list(stable_nodes)

# Cek data kosong
if len(stable_nodes) == 0:
    raise ValueError("stable_nodes kosong. Tidak ada stable overlapping node yang dapat divisualisasikan.")

if community_info_df.empty:
    raise ValueError("community_info_df kosong. Tidak ada informasi komunitas yang dapat divisualisasikan.")

# =====================================================
# 1. SIAPKAN WARNA KOMUNITAS
# =====================================================

unique_comms = sorted(community_info_df["community"].unique().tolist())

# Gunakan colormap sesuai jumlah komunitas
if len(unique_comms) <= 10:
    cmap = plt.colormaps["tab10"].resampled(len(unique_comms))
elif len(unique_comms) <= 20:
    cmap = plt.colormaps["tab20"].resampled(len(unique_comms))
else:
    cmap = plt.colormaps["hsv"].resampled(len(unique_comms))

community_colors = {
    comm: cmap(i)
    for i, comm in enumerate(unique_comms)
}

# =====================================================
# 2. ATUR POSISI NODE
# =====================================================

pos = {}

# Posisi stable overlapping nodes dibuat otomatis secara horizontal
n_stable = len(stable_nodes)

spacing = 4.5
x_positions = np.linspace(
    -spacing * (n_stable - 1) / 2,
     spacing * (n_stable - 1) / 2,
     n_stable
)

for i, node in enumerate(stable_nodes):
    pos[node] = (x_positions[i], 0)

# Posisi representative nodes di atas masing-masing overlapping node
for overlap_node in stable_nodes:

    sub = community_info_df[
        community_info_df["overlap_node"] == overlap_node
    ].reset_index(drop=True)

    if sub.empty:
        continue

    base_x, base_y = pos[overlap_node]

    n_rep = len(sub)

    for j, (_, row) in enumerate(sub.iterrows()):

        if n_rep == 1:
            dx = 0
        else:
            # Lebar penyebaran representative nodes menyesuaikan jumlahnya
            rep_width = max(2.2, 0.9 * (n_rep - 1))
            dx = -rep_width / 2 + (rep_width * j / (n_rep - 1))

        rep_node = row["rep_node_id"]
        pos[rep_node] = (base_x + dx, base_y + 2.7)

# =====================================================
# 3. CEK NODE YANG BELUM PUNYA POSISI
# =====================================================

missing_pos = [node for node in H.nodes() if node not in pos]

if missing_pos:
    print("Node berikut belum memiliki posisi dan akan diletakkan otomatis:")
    print(missing_pos)

    # Tambahkan posisi otomatis untuk node yang belum masuk pos
    extra_pos = nx.spring_layout(
        H.subgraph(missing_pos),
        seed=42
    )

    for node, p in extra_pos.items():
        pos[node] = (p[0], p[1] - 3)

# =====================================================
# 4. BUAT FIGURE
# =====================================================

fig_width = max(16, 3.2 * n_stable)

plt.figure(figsize=(fig_width, 9))

# =====================================================
# 5. GAMBAR EDGES
# =====================================================

nx.draw_networkx_edges(
    H,
    pos,
    width=1.4,
    alpha=0.65
)

# =====================================================
# 6. GAMBAR NODE OVERLAPPING
# =====================================================

nx.draw_networkx_nodes(
    H,
    pos,
    nodelist=stable_nodes,
    node_shape="D",
    node_size=2200,
    node_color="gold",
    edgecolors="black",
    linewidths=2,
    label="Stable overlapping nodes"
)

# =====================================================
# 7. GAMBAR NODE REPRESENTATIVE BERDASARKAN KOMUNITAS
# =====================================================

for comm in unique_comms:

    nodes_comm = (
        community_info_df.loc[
            community_info_df["community"] == comm,
            "rep_node_id"
        ]
        .drop_duplicates()
        .tolist()
    )

    # Ambil hanya node yang benar-benar ada di graph H
    nodes_comm = [node for node in nodes_comm if node in H.nodes()]

    if len(nodes_comm) == 0:
        continue

    nx.draw_networkx_nodes(
        H,
        pos,
        nodelist=nodes_comm,
        node_shape="o",
        node_size=1600,
        node_color=[community_colors[comm]],
        edgecolors="black",
        linewidths=1.3,
        label=f"Community {comm}"
    )

# =====================================================
# 8. LABEL STABLE OVERLAPPING NODES
# =====================================================

overlap_labels = {
    node: "\n".join(textwrap.wrap(str(node), width=20))
    for node in stable_nodes
}

nx.draw_networkx_labels(
    H,
    pos,
    labels=overlap_labels,
    font_size=8,
    font_weight="bold"
)

# =====================================================
# 9. LABEL REPRESENTATIVE NODES
# =====================================================

rep_labels = {}

for _, row in community_info_df.iterrows():

    rep_node = row["rep_node_id"]

    if rep_node not in H.nodes():
        continue

    label_text = f"{row['rep_disease']}\nC{row['community']}"

    rep_labels[rep_node] = "\n".join(
        textwrap.wrap(str(label_text), width=18)
    )

nx.draw_networkx_labels(
    H,
    pos,
    labels=rep_labels,
    font_size=7
)

# =====================================================
# 10. LEGEND
# =====================================================

handles = [
    plt.Line2D(
        [0], [0],
        marker="D",
        color="w",
        markerfacecolor="gold",
        markeredgecolor="black",
        markersize=10,
        label="Stable overlapping nodes"
    )
]

for comm in unique_comms:
    handles.append(
        plt.Line2D(
            [0], [0],
            marker="o",
            color="w",
            markerfacecolor=community_colors[comm],
            markeredgecolor="black",
            markersize=10,
            label=f"Community {comm}"
        )
    )

plt.legend(
    handles=handles,
    loc="center left",
    bbox_to_anchor=(1.02, 0.5),
    frameon=True,
    fontsize=9
)

# =====================================================
# 11. FINAL LAYOUT DAN SIMPAN GAMBAR
# =====================================================

plt.title(
    "Stable Overlapping Nodes and Representative Diseases from Connected Communities",
    fontsize=12
)

plt.axis("off")
plt.tight_layout(rect=[0, 0, 0.82, 1])

output_path = f"{out_dir}/{prefix}_stable_overlapping_nodes_representative_communities.png"

plt.savefig(
    output_path,
    dpi=300,
    bbox_inches="tight"
)

plt.show()

print("Gambar berhasil disimpan ke:")
print(output_path)

def check_overlap_membership(node_name, fuzzy_membership, alpha=0.30):
    memb = fuzzy_membership[node_name]

    passed = {
        normalize_comm_id(k): float(v)
        for k, v in memb.items()
        if float(v) >= alpha
    }

    return passed


check_overlap_membership(
    "childhood spinal muscular atrophy",
    fuzzy_membership,
    alpha=0.30
)