# -*- coding: utf-8 -*-
"""Overlapping Nodes NSCLC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_SrrD1PxFTqS9KBg7yHRaIN77mO1xNd
"""

!pip install venn

"""NSCLC"""

import json
import ast
import os
import pandas as pd
import matplotlib.pyplot as plt

# =========================
# 1. SETTING PATH
# =========================

base_dir = "/content/drive/MyDrive/dataset/Tesis/pubtator/BestRun"

prefix = "nsclc"

membership_file = os.path.join(base_dir, f"{prefix}_best_memberships.json")
summary_file = os.path.join(base_dir, f"{prefix}_best_run_summary.json")

out_dir = os.path.join(base_dir, "overlapping_threshold_sensitivity")
os.makedirs(out_dir, exist_ok=True)

thresholds = [0.30, 0.35, 0.40, 0.45, 0.50]

# =========================
# 2. LOAD BEST RUN SUMMARY
# =========================

with open(summary_file, "r") as f:
    best_summary = json.load(f)

print("=== BEST RUN SUMMARY ===")
print(json.dumps(best_summary, indent=2))


# =========================
# 3. LOAD BEST MEMBERSHIP
# =========================

with open(membership_file, "r") as f:
    raw_membership = json.load(f)

print("\nTipe data membership:", type(raw_membership))

if isinstance(raw_membership, dict):
    print("Jumlah key:", len(raw_membership))
    first_key = list(raw_membership.keys())[0]
    print("Contoh key pertama:", first_key)
    print("Contoh value:", raw_membership[first_key])
elif isinstance(raw_membership, list):
    print("Jumlah baris:", len(raw_membership))
    print("Contoh baris:", raw_membership[0])

def normalize_membership(raw_membership):
    """
    Mengubah berbagai kemungkinan format membership menjadi:

    {
        node_id: {
            community_id: membership_value,
            ...
        },
        ...
    }
    """

    # Format 1:
    # {
    #   "48": {"2": 0.92, "16": 0.08},
    #   ...
    # }
    if isinstance(raw_membership, dict):
        # Kalau ada wrapper seperti "best_memberships" atau "fuzzy_membership"
        possible_keys = [
            "best_memberships",
            "fuzzy_membership",
            "memberships",
            "membership",
            "node_memberships"
        ]

        for key in possible_keys:
            if key in raw_membership:
                raw_membership = raw_membership[key]
                break

        normalized = {}

        for node, membership_dict in raw_membership.items():

            if isinstance(membership_dict, str):
                membership_dict = ast.literal_eval(membership_dict)

            normalized[str(node)] = {
                str(comm): float(mu)
                for comm, mu in membership_dict.items()
            }

        return normalized

    # Format 2:
    # [
    #   {"node": 48, "community": 2, "membership": 0.92},
    #   {"node": 48, "community": 16, "membership": 0.08}
    # ]
    elif isinstance(raw_membership, list):
        normalized = {}

        for row in raw_membership:
            node = str(row.get("node", row.get("node_id")))
            comm = str(row.get("community", row.get("community_id", row.get("comm"))))
            mu = float(row.get("membership", row.get("mu", row.get("value"))))

            if node not in normalized:
                normalized[node] = {}

            normalized[node][comm] = mu

        return normalized

    else:
        raise ValueError("Format membership tidak dikenali.")


fuzzy_membership = normalize_membership(raw_membership)

print("Jumlah node dalam best membership:", len(fuzzy_membership))

# tampilkan contoh 5 node
for i, (node, memb) in enumerate(fuzzy_membership.items()):
    print(node, memb)
    if i == 4:
        break

def detect_overlapping_nodes(fuzzy_membership, alpha_threshold):
    """
    Node disebut overlapping jika memiliki minimal dua komunitas
    dengan nilai membership >= alpha_threshold.
    """

    rows = []

    for node, membership_dict in fuzzy_membership.items():

        memberships = {
            str(comm): float(mu)
            for comm, mu in membership_dict.items()
        }

        selected = {
            comm: mu
            for comm, mu in memberships.items()
            if mu >= alpha_threshold
        }

        sorted_memberships = sorted(
            memberships.items(),
            key=lambda x: x[1],
            reverse=True
        )

        top1_comm, top1_mu = sorted_memberships[0]

        if len(sorted_memberships) > 1:
            top2_comm, top2_mu = sorted_memberships[1]
        else:
            top2_comm, top2_mu = None, 0.0

        if len(selected) >= 2:
            rows.append({
                "node": node,
                "alpha_threshold": alpha_threshold,
                "num_selected_communities": len(selected),
                "selected_communities": list(selected.keys()),
                "selected_memberships": selected,
                "top1_community": top1_comm,
                "top1_membership": top1_mu,
                "top2_community": top2_comm,
                "top2_membership": top2_mu,
                "membership_gap_top1_top2": top1_mu - top2_mu,
                "all_memberships": memberships
            })

    return pd.DataFrame(rows)

sensitivity_rows = []
detail_all = []

total_nodes = len(fuzzy_membership)

for alpha in thresholds:
    df_overlap = detect_overlapping_nodes(
        fuzzy_membership=fuzzy_membership,
        alpha_threshold=alpha
    )

    num_overlap = len(df_overlap)
    overlap_ratio = num_overlap / total_nodes if total_nodes > 0 else 0

    overlapping_nodes = df_overlap["node"].tolist() if num_overlap > 0 else []

    sensitivity_rows.append({
        "alpha_threshold": alpha,
        "total_nodes": total_nodes,
        "num_overlapping_nodes": num_overlap,
        "overlapping_node_ratio": overlap_ratio,
        "overlapping_nodes": overlapping_nodes
    })

    # simpan detail per threshold
    df_overlap.to_csv(
        os.path.join(out_dir, f"{prefix}_overlapping_nodes_alpha_{alpha:.2f}.csv"),
        index=False
    )

    if num_overlap > 0:
        detail_all.append(df_overlap)

sensitivity_df = pd.DataFrame(sensitivity_rows)

if detail_all:
    detail_df = pd.concat(detail_all, ignore_index=True)
else:
    detail_df = pd.DataFrame()

# simpan hasil utama
sensitivity_df.to_csv(
    os.path.join(out_dir, f"{prefix}_overlapping_threshold_sensitivity_best_run.csv"),
    index=False
)

detail_df.to_csv(
    os.path.join(out_dir, f"{prefix}_overlapping_detail_all_thresholds_best_run.csv"),
    index=False
)

print("=== HASIL SENSITIVITAS THRESHOLD ===")
display(sensitivity_df)

print("=== DETAIL NODE OVERLAPPING ===")
display(detail_df)

plt.figure(figsize=(7, 5))

plt.plot(
    sensitivity_df["alpha_threshold"],
    sensitivity_df["num_overlapping_nodes"],
    marker="o"
)

plt.xlabel("Alpha Threshold")
plt.ylabel("Number of Overlapping Nodes")
plt.title(f"Sensitivity of Overlapping Nodes on {prefix.upper()} Best Run")
plt.grid(True)
plt.show()

import pandas as pd
import ast
import matplotlib.pyplot as plt

# ==========================================
# LOAD FILE RINGKASAN SENSITIVITAS
# ==========================================
base_dir = "/content/drive/MyDrive/dataset/Tesis/pubtator/BestRun/overlapping_threshold_sensitivity"
prefix = "nsclc"

summary_path = f"{base_dir}/{prefix}_overlapping_threshold_sensitivity_best_run.csv"
sensitivity_df = pd.read_csv(summary_path)

display(sensitivity_df)

def to_set(x):
    if pd.isna(x) or str(x).strip() == "":
        return set()
    if isinstance(x, list):
        return set(x)
    return set(ast.literal_eval(x))

venn_sets = {}

for _, row in sensitivity_df.iterrows():
    alpha = row["alpha_threshold"]
    label = f"α={alpha:.2f}"
    venn_sets[label] = to_set(row["overlapping_nodes"])

print(venn_sets)

from venn import venn

plt.figure(figsize=(10, 10))
venn(venn_sets)
plt.title("Venn Diagram Node Overlapping pada Berbagai Alpha Threshold")
plt.show()

from itertools import combinations
import pandas as pd

# pastikan label sesuai dengan yang ada di venn_sets
labels = ["α=0.30", "α=0.35", "α=0.40", "α=0.45", "α=0.50"]

region_rows = []

for r in range(1, len(labels) + 1):
    for combo in combinations(labels, r):

        # node yang ada di semua set dalam combo
        included = set.intersection(*(venn_sets[label] for label in combo))

        # node yang tidak boleh ada di set lain di luar combo
        excluded_labels = [label for label in labels if label not in combo]

        if excluded_labels:
            excluded = set.union(*(venn_sets[label] for label in excluded_labels))
            region_nodes = included - excluded
        else:
            region_nodes = included

        if len(region_nodes) > 0:
            region_rows.append({
                "region": " ∩ ".join(combo),
                "num_nodes": len(region_nodes),
                "nodes": sorted(region_nodes)
            })

region_df = pd.DataFrame(region_rows)

display(region_df)

region_df.to_csv(
    f"{base_dir}/{prefix}_venn_region_nodes.csv",
    index=False
)

import ast
import pandas as pd

def parse_node_list(x):
    if isinstance(x, list):
        return x
    if isinstance(x, set):
        return list(x)

    s = str(x).strip()

    try:
        val = ast.literal_eval(s)
        if isinstance(val, list):
            return val
    except:
        pass

    return [i.strip() for i in s.split(",") if i.strip()]

# ambil baris keempat / index 3
stable_nodes = parse_node_list(region_df.loc[4, "nodes"])

print("Node overlapping paling stabil:")
for n in stable_nodes:
    print("-", n)

alpha_plot = 0.5

# supaya aman kalau huruf besar/kecil berbeda
node_lookup = {
    str(node).strip().lower(): node
    for node in fuzzy_membership.keys()
}

rows = []

for node_name in stable_nodes:
    node_key = node_lookup.get(node_name.lower())

    if node_key is None:
        print(f"Node tidak ditemukan di fuzzy_membership: {node_name}")
        continue

    memberships = {
        str(comm): float(mu)
        for comm, mu in fuzzy_membership[node_key].items()
    }

    selected = {
        comm: mu
        for comm, mu in memberships.items()
        if mu >= alpha_plot
    }

    sorted_selected = sorted(
        selected.items(),
        key=lambda x: x[1],
        reverse=True
    )

    sorted_all = sorted(
        memberships.items(),
        key=lambda x: x[1],
        reverse=True
    )

    rows.append({
        "node": node_name,
        "alpha_threshold": alpha_plot,
        "overlapping_communities": [comm for comm, mu in sorted_selected],
        "membership_values": {comm: round(mu, 4) for comm, mu in sorted_selected},
        "num_overlapping_communities": len(sorted_selected),
        "dominant_community": sorted_all[0][0],
        "dominant_membership": round(sorted_all[0][1], 4),
        "second_community": sorted_all[1][0] if len(sorted_all) > 1 else None,
        "second_membership": round(sorted_all[1][1], 4) if len(sorted_all) > 1 else None,
        "membership_gap": round(sorted_all[0][1] - sorted_all[1][1], 4) if len(sorted_all) > 1 else None,
        "all_memberships": {comm: round(mu, 4) for comm, mu in sorted_all}
    })

stable_overlap_df = pd.DataFrame(rows)

display(stable_overlap_df)

stable_overlap_df.to_csv(
    f"{out_dir}/{prefix}_stable_overlapping_nodes_communities_alpha_05.csv",
    index=False
)

import pandas as pd
import ast
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import math
import textwrap

# kalau stable_overlap_df hasil load dari csv
# stable_overlap_df = pd.read_csv(f"{out_dir}/{prefix}_stable_overlapping_nodes_communities_alpha_05.csv")

plot_source_df = stable_overlap_df.copy()

# karena kolom kamu namanya "node", ubah jadi "overlapping_node"
if "overlapping_node" not in plot_source_df.columns:
    if "node" in plot_source_df.columns:
        plot_source_df = plot_source_df.rename(columns={"node": "overlapping_node"})
    else:
        raise ValueError("Kolom node / overlapping_node tidak ditemukan.")

display(plot_source_df.head())

def normalize_comm_id(x):
    try:
        return str(int(float(x)))
    except:
        return str(x)

def parse_list_or_dict(x):
    if isinstance(x, (list, dict)):
        return x
    return ast.literal_eval(str(x))

stable_nodes = [
    "lymphoid interstitial pneumonia",
    "multiple sclerosis",
    "pulmonary embolism",
    "systemic lupus erythematosus"
]

plot_rows = []

for _, row in plot_source_df.iterrows():
    overlap_node = row["overlapping_node"]

    if overlap_node not in stable_nodes:
        continue

    overlapping_communities = parse_list_or_dict(row["overlapping_communities"])
    membership_values = parse_list_or_dict(row["membership_values"])

    for comm in overlapping_communities:
        comm_id = normalize_comm_id(comm)

        plot_rows.append({
            "overlapping_node": overlap_node,
            "internal_community_label": comm_id,
            "membership_value": membership_values.get(comm_id, membership_values.get(comm, None))
        })

plot_df = pd.DataFrame(plot_rows)

display(plot_df)

alpha_member = 0.50

def norm_text(x):
    return str(x).strip().lower()


def get_members_of_internal_community(comm_id, fuzzy_membership, alpha_member=0.30):
    members = []

    comm_id = normalize_comm_id(comm_id)

    for node, memb in fuzzy_membership.items():
        memb_norm = {
            normalize_comm_id(k): float(v)
            for k, v in memb.items()
        }

        if comm_id in memb_norm and memb_norm[comm_id] >= alpha_member:
            members.append((str(node), memb_norm[comm_id]))

    members = sorted(members, key=lambda x: x[1], reverse=True)
    return members


def choose_representative_disease_unique(
    comm_id,
    overlap_node,
    fuzzy_membership,
    G,
    stable_nodes,
    used_representatives,
    representative_cache,
    alpha_member=0.30
):
    comm_id = normalize_comm_id(comm_id)

    if comm_id in representative_cache:
        return representative_cache[comm_id]

    members = get_members_of_internal_community(
        comm_id=comm_id,
        fuzzy_membership=fuzzy_membership,
        alpha_member=alpha_member
    )

    stable_lc = {norm_text(s) for s in stable_nodes}
    used_lc = {norm_text(u) for u in used_representatives}
    overlap_lc = norm_text(overlap_node)

    # daftar label generik yang tidak boleh dijadikan representative
    banned_labels = {
        "cancer",
        "tumor",
        "neoplasm",
        "malignant neoplasm",
        "carcinoma"
    }

    graph_lookup = {
        norm_text(n): n
        for n in G.nodes()
    }

    candidates = []

    for node, mu in members:
        node_lc = norm_text(node)

        # skip stable overlapping nodes
        if node_lc in stable_lc:
            continue

        # skip overlap node itu sendiri
        if node_lc == overlap_lc:
            continue

        # skip representative yang sudah dipakai
        if node_lc in used_lc:
            continue

        # skip label terlalu umum
        if node_lc in banned_labels:
            continue

        if node_lc in graph_lookup:
            actual_node = graph_lookup[node_lc]
            degree = G.degree(actual_node)
        else:
            actual_node = node
            degree = 0

        candidates.append({
            "node": str(actual_node),
            "membership": mu,
            "degree": degree
        })

    if len(candidates) > 0:
        candidates = sorted(
            candidates,
            key=lambda x: (x["degree"], x["membership"]),
            reverse=True
        )

        chosen = candidates[0]["node"]
        used_representatives.add(chosen)
        representative_cache[comm_id] = chosen
        return chosen

    # fallback kalau semua kandidat terfilter
    fallback_label = f"Community {comm_id}"
    representative_cache[comm_id] = fallback_label
    return fallback_label

import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

graph_path = "/content/drive/MyDrive/dataset/Tesis/pubtator/nsclc_disease_pub.csv"

df_edge = pd.read_csv(graph_path)

print(df_edge.head())
print(df_edge.columns)

def load_graph_from_csv(df):
    possible_pairs = [
        ("source", "target"),
        ("Source", "Target"),
        ("node1", "node2"),
        ("disease1", "disease2"),
        ("disease_a", "disease_b"),
        ("from", "to"),
        ("u", "v")
    ]

    source_col, target_col = None, None

    for a, b in possible_pairs:
        if a in df.columns and b in df.columns:
            source_col, target_col = a, b
            break

    if source_col is None:
        source_col, target_col = df.columns[0], df.columns[1]

    weight_col = None
    for col in ["weight", "similarity", "score", "wang_similarity"]:
        if col in df.columns:
            weight_col = col
            break

    G = nx.Graph()

    for _, row in df.iterrows():
        u = str(row[source_col]).strip()
        v = str(row[target_col]).strip()

        if weight_col is not None:
            w = float(row[weight_col])
        else:
            w = 1.0

        G.add_edge(u, v, weight=w)

    return G

G = load_graph_from_csv(df_edge)

print("Jumlah node:", G.number_of_nodes())
print("Jumlah edge:", G.number_of_edges())

stable_nodes_actual = []

graph_node_lookup = {
    str(node).strip().lower(): node
    for node in G.nodes()
}

for node in stable_nodes:
    key = graph_node_lookup.get(node.lower())
    if key is not None:
        stable_nodes_actual.append(key)
    else:
        print("Tidak ditemukan di graph:", node)

plot_nodes = set(stable_nodes_actual)

for node in stable_nodes_actual:
    plot_nodes.update(G.neighbors(node))

subG = G.subgraph(plot_nodes).copy()

print("Jumlah node pada subnetwork:", subG.number_of_nodes())
print("Jumlah edge pada subnetwork:", subG.number_of_edges())

H = nx.Graph()

for node in stable_nodes:
    H.add_node(node, kind="overlap", label=node)

community_info = []

used_representatives = set()
representative_cache = {}

for _, row in plot_df.iterrows():
    overlap_node = row["overlapping_node"]
    comm_id = row["internal_community_label"]
    membership_value = row["membership_value"]

    rep_disease = choose_representative_disease_unique(
        comm_id=comm_id,
        overlap_node=overlap_node,
        fuzzy_membership=fuzzy_membership,
        G=subG,
        stable_nodes=stable_nodes,
        used_representatives=used_representatives,
        representative_cache=representative_cache,
        alpha_member=0.30
    )

    if rep_disease is None:
        continue

    comm_label = str(comm_id)
    if not comm_label.startswith("C"):
        comm_label = f"C{comm_label}"

    rep_node_id = f"{comm_label}__{rep_disease}"

    H.add_node(
        rep_node_id,
        kind="representative",
        label=rep_disease,
        community=comm_id
    )

    H.add_edge(overlap_node, rep_node_id, weight=membership_value)

    community_info.append({
        "overlap_node": overlap_node,
        "community": comm_id,
        "rep_node_id": rep_node_id,
        "rep_disease": rep_disease,
        "membership_value": membership_value
    })

community_info_df = pd.DataFrame(community_info)
display(community_info_df)

plt.figure(figsize=(16, 9))

unique_comms = sorted(community_info_df["community"].unique().tolist())

cmap = plt.cm.get_cmap("tab10", len(unique_comms))
community_colors = {
    comm: cmap(i)
    for i, comm in enumerate(unique_comms)
}

# posisi node overlapping horizontal
pos = {}

x_positions = [-6, -2, 2, 6]

for i, node in enumerate(stable_nodes):
    pos[node] = (x_positions[i], 0)

# posisi representative nodes di atas masing-masing overlapping node
for overlap_node in stable_nodes:
    sub = community_info_df[
        community_info_df["overlap_node"] == overlap_node
    ].reset_index(drop=True)

    base_x, base_y = pos[overlap_node]

    for j, (_, row) in enumerate(sub.iterrows()):
        if len(sub) == 1:
            dx = 0
        else:
            dx = -1.1 + (2.2 * j / (len(sub) - 1))

        pos[row["rep_node_id"]] = (base_x + dx, base_y + 2.5)

# edges
nx.draw_networkx_edges(
    H,
    pos,
    width=1.4,
    alpha=0.65
)

# node overlapping: diamond
nx.draw_networkx_nodes(
    H,
    pos,
    nodelist=stable_nodes,
    node_shape="D",
    node_size=2200,
    node_color="gold",
    edgecolors="black",
    linewidths=2,
    label="Stable overlapping nodes"
)

# node representative: bulat, warna per komunitas
for comm in unique_comms:
    nodes_comm = community_info_df.loc[
        community_info_df["community"] == comm,
        "rep_node_id"
    ].tolist()

    nx.draw_networkx_nodes(
        H,
        pos,
        nodelist=nodes_comm,
        node_shape="o",
        node_size=1600,
        node_color=[community_colors[comm]],
        edgecolors="black",
        linewidths=1.3,
        label=f"Community {comm}"
    )

# label overlapping nodes
overlap_labels = {
    node: "\n".join(textwrap.wrap(node, width=20))
    for node in stable_nodes
}

nx.draw_networkx_labels(
    H,
    pos,
    labels=overlap_labels,
    font_size=8,
    font_weight="bold"
)

# label representative nodes
rep_labels = {}

for _, row in community_info_df.iterrows():
    label_text = f"{row['rep_disease']}\nC{row['community']}"
    rep_labels[row["rep_node_id"]] = "\n".join(textwrap.wrap(label_text, width=18))

nx.draw_networkx_labels(
    H,
    pos,
    labels=rep_labels,
    font_size=7
)

# legend
handles = [
    plt.Line2D(
        [0], [0],
        marker="D",
        color="w",
        markerfacecolor="gold",
        markeredgecolor="black",
        markersize=10,
        label="Stable overlapping nodes"
    )
]

for comm in unique_comms:
    handles.append(
        plt.Line2D(
            [0], [0],
            marker="o",
            color="w",
            markerfacecolor=community_colors[comm],
            markeredgecolor="black",
            markersize=10,
            label=f"Community {comm}"
        )
    )

plt.legend(
    handles=handles,
    loc="center left",
    bbox_to_anchor=(1.02, 0.5),
    frameon=True,
    fontsize=9
)

plt.tight_layout(rect=[0, 0, 0.82, 1])
plt.title("Stable Overlapping Nodes and Representative Diseases from Connected Communities")
plt.axis("off")
plt.tight_layout(rect=[0, 0, 0.82, 1])

plt.savefig(
    f"{out_dir}/{prefix}_stable_overlapping_nodes_representative_communities.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

import networkx as nx
import matplotlib.pyplot as plt

B = nx.Graph()

stable_node_set = set(stable_overlap_df["node"])
community_nodes = set()

for _, row in stable_overlap_df.iterrows():
    disease_node = row["node"]
    communities = row["overlapping_communities"]
    memberships = row["membership_values"]

    B.add_node(disease_node, node_type="disease")

    for comm in communities:
        comm_node = f"C{comm}"
        community_nodes.add(comm_node)

        B.add_node(comm_node, node_type="community")
        B.add_edge(
            disease_node,
            comm_node,
            weight=memberships[comm]
        )

# layout bipartite manual
pos = {}

disease_nodes = list(stable_node_set)
community_nodes = sorted(list(community_nodes))

for i, node in enumerate(disease_nodes):
    pos[node] = (0, i)

for i, comm in enumerate(community_nodes):
    pos[comm] = (1.7, i)

plt.figure(figsize=(10, 6))

nx.draw_networkx_edges(
    B,
    pos,
    width=1.5,
    alpha=0.7
)

nx.draw_networkx_nodes(
    B,
    pos,
    nodelist=disease_nodes,
    node_shape="D",
    node_size=1200,
    label="Stable overlapping nodes"
)

nx.draw_networkx_nodes(
    B,
    pos,
    nodelist=community_nodes,
    node_shape="s",
    node_size=1000,
    label="Communities"
)

nx.draw_networkx_labels(
    B,
    pos,
    font_size=8
)

edge_labels = {
    (u, v): f"{d['weight']:.3f}"
    for u, v, d in B.edges(data=True)
}

nx.draw_networkx_edge_labels(
    B,
    pos,
    edge_labels=edge_labels,
    font_size=8
)

plt.title("Stable Overlapping Nodes and Their Overlapping Communities at α=0.5")
plt.axis("off")
plt.legend()
plt.tight_layout()

plt.savefig(
    f"{out_dir}/{prefix}_stable_overlapping_node_community_network_alpha_05.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()