# -*- coding: utf-8 -*-
"""Analisa PCA dan topologi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fdkh7q0rLPVJrivhXMc2W1qENrB7Y0NV
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

# Load data
df = pd.read_excel("/content/drive/MyDrive/dataset/Tesis/hasil evaluasi.xlsx")  # ganti path jika perlu

# Ambil metrik dan hitung rata-rata per model
metrics = ['ONMI', 'Omega', 'Comm_P', 'Comm_R', 'Comm_F1']
df_mean = df.groupby('Model')[metrics].mean()

# (Opsional) Normalisasi per metrik agar clustering lebih adil (z-score)
scaler = StandardScaler()
df_scaled = pd.DataFrame(
    scaler.fit_transform(df_mean),
    index=df_mean.index,
    columns=df_mean.columns
)

# Clustermap (dengan dendrogram)
cg = sns.clustermap(
    df_scaled,
    method="ward",  # metode linkage
    metric="euclidean",  # jenis jarak antar baris
    cmap="coolwarm",
    figsize=(10, 6),
    annot=True,
    fmt=".2f",
    linewidths=0.5,
    cbar_kws={"label": "Z-score"},
)

# Tambahkan judul dan tampilkan
#plt.suptitle("Clustermap Model × Metrik (Z-Score)", y=1.05)
plt.show()

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# ===============================
# 1. Load data evaluasi
# ===============================
file_path = "/content/drive/MyDrive/dataset/Tesis/hasil evaluasi.xlsx"
df = pd.read_excel(file_path)

# ===============================
# 2. Tentukan kolom untuk PCA
# ===============================

# Metrik utama: semakin besar semakin baik
positive_metrics = [
    "ONMI",
    "Omega",
    "Comm_P",
    "Comm_R",
    "Comm_F1"
]
std_metrics = [
    "std_ONMI",
    "std_Omega",
    "std_CommP",
    "std_CommR",
    "std_CommF1"
]


# Salin data numerik
X = df[positive_metrics + std_metrics].copy()


# ===============================
# 3. Standardisasi data
# ===============================
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# ===============================
# 4. PCA
# ===============================
pca = PCA(n_components=1)
pc1 = pca.fit_transform(X_scaled)

# Masukkan hasil PC1 ke dataframe
df["PC1"] = pc1[:, 0]

# ===============================
# 5. Koreksi arah PC1
# ===============================
# Dalam PCA, tanda PC1 bisa positif atau negatif secara arbitrer.
# Supaya nilai PC1 yang lebih besar berarti performa lebih baik,
# arah PC1 disesuaikan dengan rata-rata metrik utama.

quality_mean = df[positive_metrics].mean(axis=1)

if np.corrcoef(df["PC1"], quality_mean)[0, 1] < 0:
    df["PC1"] = -df["PC1"]

# ===============================
# 6. Normalisasi PC1 ke skala 0-1
# ===============================
df["PC1_norm"] = (
    (df["PC1"] - df["PC1"].min()) /
    (df["PC1"].max() - df["PC1"].min())
)

# ===============================
# 7. Ranking per dataset
# ===============================
df["Rank_PC1"] = df.groupby("Data")["PC1_norm"].rank(
    ascending=False,
    method="dense"
).astype(int)

# ===============================
# 8. Simpan hasil
# ===============================
output_path = "hasil_evaluasi_dengan_PC1.xlsx"
df.to_excel(output_path, index=False)

# ===============================
# 9. Tampilkan hasil ringkas
# ===============================
print("Explained variance ratio PC1:", pca.explained_variance_ratio_[0])
print(df[["Data", "Model", "PC1", "PC1_norm", "Rank_PC1"]])

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# =========================================================
# 1. Persiapan data
# =========================================================
df_plot = df.copy()

df_plot["PC1_norm"] = pd.to_numeric(
    df_plot["PC1_norm"],
    errors="coerce"
)

df_plot = df_plot.dropna(
    subset=["Data", "Model", "PC1_norm"]
).copy()

dataset_order = [
    "Karate",
    "Dolphin",
    "Football",
    "Yeast",
    "Y2H"
]

missing_datasets = [
    dataset
    for dataset in dataset_order
    if dataset not in df_plot["Data"].unique()
]

if missing_datasets:
    raise ValueError(
        f"Dataset berikut tidak ditemukan: {missing_datasets}"
    )

# =========================================================
# 2. Pengaturan figure
# =========================================================
# Susunan panel:
# Baris 1: Karate, Dolphin
# Baris 2: Football, Yeast
# Baris 3: Y2H di sebelah kiri
fig = plt.figure(figsize=(12, 13))

gs = fig.add_gridspec(
    nrows=3,
    ncols=2,
    hspace=0.78,
    wspace=0.25
)

panel_positions = [
    gs[0, 0],  # (a) Karate
    gs[0, 1],  # (b) Dolphin
    gs[1, 0],  # (c) Football
    gs[1, 1],  # (d) Yeast
    gs[2, 0]   # (e) Y2H
]

panel_labels = [
    "(a)",
    "(b)",
    "(c)",
    "(d)",
    "(e)"
]

y_max = df_plot["PC1_norm"].max()
y_upper = y_max * 1.18

axes = []

# =========================================================
# 3. Membuat setiap panel
# =========================================================
for i, (dataset_name, position, panel_label) in enumerate(
    zip(dataset_order, panel_positions, panel_labels)
):

    if i == 0:
        ax = fig.add_subplot(position)
    else:
        ax = fig.add_subplot(
            position,
            sharey=axes[0]
        )

    axes.append(ax)

    subset = (
        df_plot[df_plot["Data"] == dataset_name]
        .sort_values(
            by="PC1_norm",
            ascending=False
        )
        .reset_index(drop=True)
    )

    x = np.arange(len(subset))

    bars = ax.bar(
        x,
        subset["PC1_norm"],
        width=0.76
    )

    # Label model
    ax.set_xticks(x)
    ax.set_xticklabels(
        subset["Model"].astype(str),
        rotation=90,
        ha="center",
        fontsize=9
    )

    ax.tick_params(
        axis="x",
        length=0,
        pad=4
    )

    ax.tick_params(
        axis="y",
        labelsize=9
    )

    ax.set_ylim(
        0,
        y_upper
    )

    ax.set_xlim(
        -0.6,
        len(subset) - 0.4
    )

    # Judul dataset
    ax.set_title(
        dataset_name,
        fontsize=12,
        fontweight="bold",
        pad=8
    )

    # Label panel
    ax.text(
        0.015,
        0.975,
        panel_label,
        transform=ax.transAxes,
        ha="left",
        va="top",
        fontsize=11,
        fontweight="bold"
    )

    # Nilai pada batang
    for bar, value in zip(
        bars,
        subset["PC1_norm"]
    ):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + y_max * 0.012,
            f"{value:.3f}",
            ha="center",
            va="bottom",
            fontsize=8,
            rotation=90
        )

    ax.grid(
        axis="y",
        linestyle=":",
        linewidth=0.5,
        alpha=0.45
    )

    ax.set_axisbelow(True)
    ax.set_xlabel("")

# =========================================================
# 4. Label sumbu-y
# =========================================================
# Label hanya pada panel kiri setiap baris
left_panels = [0, 2, 4]

for i, ax in enumerate(axes):

    if i in left_panels:
        ax.set_ylabel(
            "PC1_norm",
            fontsize=10
        )

        ax.tick_params(
            axis="y",
            labelleft=True
        )

    else:
        ax.set_ylabel("")

        ax.tick_params(
            axis="y",
            labelleft=False
        )

# =========================================================
# 5. Penyesuaian margin
# =========================================================
fig.subplots_adjust(
    left=0.09,
    right=0.98,
    top=0.97,
    bottom=0.07
)

# =========================================================
# 6. Simpan gambar
# =========================================================
# SVG direkomendasikan untuk Word karena tetap tajam
fig.savefig(
    "PC1_norm_algorithm_ranking.svg",
    format="svg",
    bbox_inches="tight"
)

# Versi PNG resolusi tinggi sebagai cadangan
fig.savefig(
    "PC1_norm_algorithm_ranking.png",
    dpi=600,
    bbox_inches="tight"
)

plt.show()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# ===============================
# Ranking PC1_norm per dataset
# ===============================
df["Rank_PC1"] = df.groupby("Data")["PC1_norm"].rank(
    ascending=False,
    method="dense"
).astype(int)

# Pertahankan urutan dataset sesuai urutan asli di dataframe
dataset_order = df["Data"].drop_duplicates().tolist()

df["Data"] = pd.Categorical(
    df["Data"],
    categories=dataset_order,
    ordered=True
)

# Urutkan: per dataset, lalu ranking terbaik
df_plot = df.sort_values(
    by=["Data", "Rank_PC1", "PC1_norm"],
    ascending=[True, True, False]
).reset_index(drop=True)

# Label batang: ranking + nama model
df_plot["Bar_Label"] = (
    df_plot["Model"].astype(str)
)

# ===============================
# Plot diagram batang
# ===============================
x = np.arange(len(df_plot))

plt.figure(figsize=(18, 7))

bars = plt.bar(
    x,
    df_plot["PC1_norm"]
)

plt.xticks(
    x,
    df_plot["Bar_Label"],
    rotation=90,
    fontsize=8
)

plt.ylabel("PC1_Norm")
plt.xlabel("Models")
#plt.title("Ranking Model Berdasarkan PC1_norm per Dataset")

# ===============================
# Tambahkan nilai PC1_norm di atas batang
# ===============================
for bar, value in zip(bars, df_plot["PC1_norm"]):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height(),
        f"{value:.3f}",
        ha="center",
        va="bottom",
        fontsize=7,
        rotation=90
    )

# ===============================
# Tambahkan pemisah dan nama dataset
# ===============================
y_max = df_plot["PC1_norm"].max()

start = 0
for data_name in dataset_order:
    subset_len = len(df_plot[df_plot["Data"] == data_name])
    end = start + subset_len - 1
    center = (start + end) / 2

    # Nama dataset di atas kelompok batang
    plt.text(
        center,
        y_max * 1.12,
        str(data_name),
        ha="center",
        va="bottom",
        fontsize=10,
        fontweight="bold"
    )

    # Garis pemisah antar dataset
    plt.axvline(
        end + 0.5,
        linestyle="--",
        linewidth=0.8
    )

    start = end + 1

plt.ylim(0, y_max * 1.25)
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

# ===============================
# Data karakteristik topologi
# ===============================
topology_df = pd.DataFrame({
    "Group": [
        "Benchmark", "Benchmark", "Benchmark", "Benchmark", "Benchmark",
        "Comorbidities", "Comorbidities"
    ],
    "Dataset": [
        "Karate", "Dolphin", "Football", "Yeast_D2", "Y2H",
        "NSCLC", "SCLC"
    ],
    "Mean": [4.5882, 5.1290, 10.6609, 9.6923, 2.7518, 6.5952, 6.7973],
    "Median": [3.0, 5.0, 11.0, 6.0, 1.0, 5.0, 6.0],
    "Maximum": [17, 12, 12, 59, 89, 34, 33],
    "Skewness": [2.0009, 0.2915, -1.3260, 1.7389, 9.8821, 1.7057, 1.5511],
    "Gini": [0.3854, 0.3250, 0.0400, 0.4720, 0.4906, 0.4029, 0.4115]
})

metrics = ["Median","Mean","Skewness", "Gini"]
#metrics = ["Skewness", "Gini"]
# ===============================
# Standardisasi metrik topologi
# ===============================
scaler = StandardScaler()
X_scaled = scaler.fit_transform(topology_df[metrics])

z_topology = pd.DataFrame(
    X_scaled,
    columns=metrics,
    index=topology_df["Dataset"]
)

# ===============================
# Hitung jarak Euclidean
# ===============================
benchmark_datasets = ["Karate", "Dolphin", "Football", "Yeast_D2", "Y2H"]
comorbidity_datasets = ["NSCLC", "SCLC"]

distance_rows = []

for comorbidity in comorbidity_datasets:
    for benchmark in benchmark_datasets:
        distance = np.linalg.norm(
            z_topology.loc[comorbidity] - z_topology.loc[benchmark]
        )
        distance_rows.append({
            "Comorbidity": comorbidity,
            "Benchmark": benchmark,
            "Topology_Distance": distance
        })

distance_df = pd.DataFrame(distance_rows)

# ===============================
# Tampilkan tabel jarak
# ===============================
#print(distance_df.sort_values(["Comorbidity", "Topology_Distance"]))


# ===============================
# Visualisasi topological distance
# NSCLC dan SCLC berdampingan
# ===============================

comorbidity_order = ["NSCLC", "SCLC"]

fig, axes = plt.subplots(1, 2, figsize=(14, 4.5), sharey=True)

# Supaya skala y sama untuk NSCLC dan SCLC
y_max = distance_df["Topology_Distance"].max() * 1.15

for i, (ax, comorbidity) in enumerate(zip(axes, comorbidity_order)):
    subset = distance_df[distance_df["Comorbidity"] == comorbidity]
    subset = subset.sort_values("Topology_Distance", ascending=True)

    bars = ax.bar(
        subset["Benchmark"],
        subset["Topology_Distance"]
    )

    # Judul subplot dengan label (a) dan (b)
    label = "(a)" if i == 0 else "(b)"
    ax.set_title(
        f"{label} Topological Distance between {comorbidity} and Benchmark Network",
        fontsize=11
    )

    ax.set_xlabel("Benchmark dataset")
    ax.set_ylabel("Topological distance")
    ax.set_ylim(0, y_max)

    ax.tick_params(axis="x", rotation=45)

    # Tambahkan nilai di atas batang
    for bar, value in zip(bars, subset["Topology_Distance"]):
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height(),
            f"{value:.3f}",
            ha="center",
            va="bottom",
            fontsize=8
        )

plt.tight_layout()
plt.show()

# ============================================================
# ANALISIS TOPOLOGI-PERFORMA:
# 1. Spearman correlation
# 2. Leave-one-network-out validation
# 3. Decision score NSCLC/SCLC
# ============================================================

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from scipy.stats import spearmanr

# ------------------------------------------------------------
# 0. PENYESUAIAN NAMA DATASET
# ------------------------------------------------------------
# Samakan nama dataset antara df hasil evaluasi dan topology_df
name_map = {
    "Yeast": "Yeast_D2",
    "Yeast-MIPS": "Yeast_D2",
    "Yeast_MIPS": "Yeast_D2",
    "Dolphins": "Dolphin"
}

df = df.copy()
topology_df = topology_df.copy()

df["Data"] = df["Data"].astype(str).replace(name_map)
topology_df["Dataset"] = topology_df["Dataset"].astype(str).replace(name_map)

# ------------------------------------------------------------
# 1. PARAMETER UTAMA
# ------------------------------------------------------------
benchmark_datasets = ["Karate", "Dolphin", "Football", "Yeast_D2", "Y2H"]
target_datasets = ["NSCLC", "SCLC"]

topology_features = [
    "Mean",
    "Median",
    "Maximum",
    "Skewness",
    "Gini"
]

performance_metrics = [
    "ONMI",
    "Omega",
    "Comm_F1",
    "PC1_norm"
]

EPS = 1e-12

# Pastikan PC1_norm sudah ada
if "PC1_norm" not in df.columns:
    raise ValueError("Kolom PC1_norm belum ada. Jalankan bagian PCA terlebih dahulu.")

# ------------------------------------------------------------
# 2. DATA RINGKAS PER DATASET-MODEL
# ------------------------------------------------------------
# Jika ada beberapa baris per Data-Model, diambil rata-rata
available_perf_cols = [c for c in performance_metrics if c in df.columns]

df_perf = (
    df.groupby(["Data", "Model"], as_index=False)[available_perf_cols]
    .mean()
)

topology_indexed = topology_df.set_index("Dataset")

# ============================================================
# 1. SPEARMAN CORRELATION
# ============================================================

def compute_spearman_topology_performance(
    df_perf,
    topology_df,
    benchmark_datasets,
    topology_cols=("Skewness", "Gini"),
    performance_cols=("ONMI", "Omega", "Comm_F1", "PC1_norm")
):
    topology_sub = topology_df[
        topology_df["Dataset"].isin(benchmark_datasets)
    ][["Dataset"] + list(topology_cols)].copy()

    perf_sub = df_perf[
        df_perf["Data"].isin(benchmark_datasets)
    ].copy()

    merged = perf_sub.merge(
        topology_sub,
        left_on="Data",
        right_on="Dataset",
        how="inner"
    )

    rows = []

    for model in sorted(merged["Model"].unique()):
        model_df = merged[merged["Model"] == model].copy()

        for topo_col in topology_cols:
            for perf_col in performance_cols:

                if perf_col not in model_df.columns:
                    continue

                temp = model_df[[topo_col, perf_col]].dropna()

                if len(temp) < 3:
                    rho, pval = np.nan, np.nan
                else:
                    rho, pval = spearmanr(temp[topo_col], temp[perf_col])

                rows.append({
                    "Model": model,
                    "Topology_Feature": topo_col,
                    "Performance_Metric": perf_col,
                    "N": len(temp),
                    "Spearman_rho": rho,
                    "p_value": pval
                })

    result = pd.DataFrame(rows)
    return result


spearman_result = compute_spearman_topology_performance(
    df_perf=df_perf,
    topology_df=topology_df,
    benchmark_datasets=benchmark_datasets,
    topology_cols=("Skewness", "Gini"),
    performance_cols=("ONMI", "Omega", "Comm_F1", "PC1_norm")
)

print("=== Spearman correlation: topologi vs performa ===")
display(spearman_result)

spearman_result.to_excel(
    "/content/drive/MyDrive/dataset/Tesis/spearman_topology_performance.xlsx",
    index=False
)

# ============================================================
# 2. LEAVE-ONE-NETWORK-OUT VALIDATION
# ============================================================

def compute_topological_distance(
    topology_df,
    target_dataset,
    reference_datasets,
    topology_features,
    fit_scaler_on_reference=True
):
    topo = topology_df.set_index("Dataset")

    if fit_scaler_on_reference:
        scaler = StandardScaler()
        scaler.fit(topo.loc[reference_datasets, topology_features])

        z_reference = pd.DataFrame(
            scaler.transform(topo.loc[reference_datasets, topology_features]),
            index=reference_datasets,
            columns=topology_features
        )

        z_target = pd.Series(
            scaler.transform(topo.loc[[target_dataset], topology_features])[0],
            index=topology_features,
            name=target_dataset
        )
    else:
        all_datasets = list(reference_datasets) + [target_dataset]

        scaler = StandardScaler()
        z_all = pd.DataFrame(
            scaler.fit_transform(topo.loc[all_datasets, topology_features]),
            index=all_datasets,
            columns=topology_features
        )

        z_reference = z_all.loc[reference_datasets]
        z_target = z_all.loc[target_dataset]

    rows = []

    for ref in reference_datasets:
        distance = np.linalg.norm(z_target - z_reference.loc[ref])

        rows.append({
            "Target": target_dataset,
            "Reference": ref,
            "Topology_Distance": distance
        })

    return pd.DataFrame(rows)


def add_inverse_distance_weight(distance_df, eps=1e-12):
    result = distance_df.copy()

    result["Inverse_Distance"] = 1 / (result["Topology_Distance"] + eps)

    result["Weight"] = (
        result["Inverse_Distance"] /
        result.groupby("Target")["Inverse_Distance"].transform("sum")
    )

    return result


def compute_decision_score_from_references(
    df_perf,
    distance_weight_df,
    target_dataset,
    reference_col="Reference",
    performance_col="PC1_norm"
):
    ref_weights = distance_weight_df[
        distance_weight_df["Target"] == target_dataset
    ].copy()

    temp = df_perf[
        df_perf["Data"].isin(ref_weights[reference_col])
    ][["Data", "Model", performance_col]].copy()

    temp = temp.merge(
        ref_weights[[reference_col, "Topology_Distance", "Weight"]],
        left_on="Data",
        right_on=reference_col,
        how="inner"
    )

    temp["Weighted_Performance"] = temp[performance_col] * temp["Weight"]

    decision = (
        temp.groupby("Model", as_index=False)
        .agg(
            Decision_Score=("Weighted_Performance", "sum")
        )
        .sort_values("Decision_Score", ascending=False)
        .reset_index(drop=True)
    )

    decision["Predicted_Rank"] = decision.index + 1

    return decision


def leave_one_network_out_validation(
    df_perf,
    topology_df,
    benchmark_datasets,
    topology_features,
    performance_col="PC1_norm"
):
    summary_rows = []
    all_rank_rows = []
    all_distance_rows = []

    for target in benchmark_datasets:

        references = [d for d in benchmark_datasets if d != target]

        # Hitung jarak topologi target terhadap jaringan referensi
        distance_df = compute_topological_distance(
            topology_df=topology_df,
            target_dataset=target,
            reference_datasets=references,
            topology_features=topology_features,
            fit_scaler_on_reference=True
        )

        distance_weight_df = add_inverse_distance_weight(distance_df)
        all_distance_rows.append(distance_weight_df)

        # Prediksi peringkat algoritma dari jaringan referensi
        pred_rank = compute_decision_score_from_references(
            df_perf=df_perf,
            distance_weight_df=distance_weight_df,
            target_dataset=target,
            performance_col=performance_col
        )

        # Peringkat aktual pada jaringan target
        actual_rank = (
            df_perf[df_perf["Data"] == target][["Model", performance_col]]
            .copy()
            .sort_values(performance_col, ascending=False)
            .reset_index(drop=True)
        )

        actual_rank["Actual_Rank"] = actual_rank.index + 1
        actual_rank = actual_rank.rename(
            columns={performance_col: "Actual_PC1_norm"}
        )

        # Gabungkan prediksi dan aktual
        compare = pred_rank.merge(
            actual_rank,
            on="Model",
            how="inner"
        )

        compare["Target"] = target

        # Ranking berbasis urutan
        compare["Predicted_Rank_for_Corr"] = compare["Decision_Score"].rank(
            ascending=False,
            method="average"
        )

        compare["Actual_Rank_for_Corr"] = compare["Actual_PC1_norm"].rank(
            ascending=False,
            method="average"
        )

        if len(compare) >= 3:
            rho, pval = spearmanr(
                compare["Predicted_Rank_for_Corr"],
                compare["Actual_Rank_for_Corr"]
            )
        else:
            rho, pval = np.nan, np.nan

        predicted_top1 = compare.sort_values(
            "Predicted_Rank"
        ).iloc[0]["Model"]

        actual_top1 = compare.sort_values(
            "Actual_Rank"
        ).iloc[0]["Model"]

        predicted_top3 = set(
            compare.sort_values("Predicted_Rank")
            .head(3)["Model"]
        )

        actual_top3 = set(
            compare.sort_values("Actual_Rank")
            .head(3)["Model"]
        )

        top3_intersection = len(predicted_top3.intersection(actual_top3))

        nearest_reference = (
            distance_weight_df
            .sort_values("Topology_Distance")
            .iloc[0]["Reference"]
        )

        summary_rows.append({
            "Target_Network": target,
            "Nearest_Reference": nearest_reference,
            "Predicted_Top1": predicted_top1,
            "Actual_Top1": actual_top1,
            "Top1_Exact_Hit": predicted_top1 == actual_top1,
            "Predicted_Top1_in_Actual_Top3": predicted_top1 in actual_top3,
            "Top3_Intersection": top3_intersection,
            "Top3_Intersection_Rate": top3_intersection / 3,
            "Rank_Spearman_rho": rho,
            "Rank_Spearman_p_value": pval
        })

        all_rank_rows.append(compare)

    summary_df = pd.DataFrame(summary_rows)
    rank_detail_df = pd.concat(all_rank_rows, ignore_index=True)
    distance_detail_df = pd.concat(all_distance_rows, ignore_index=True)

    return summary_df, rank_detail_df, distance_detail_df


loo_summary, loo_rank_detail, loo_distance_detail = leave_one_network_out_validation(
    df_perf=df_perf,
    topology_df=topology_df,
    benchmark_datasets=benchmark_datasets,
    topology_features=topology_features,
    performance_col="PC1_norm"
)

print("=== Ringkasan leave-one-network-out validation ===")
display(loo_summary)

print("=== Detail ranking prediksi vs aktual ===")
display(loo_rank_detail)

print("=== Detail jarak dan bobot leave-one-network-out ===")
display(loo_distance_detail)

loo_summary.to_excel("leave_one_network_out_summary.xlsx", index=False)
loo_rank_detail.to_excel("leave_one_network_out_rank_detail.xlsx", index=False)
loo_distance_detail.to_excel("leave_one_network_out_distance_weight.xlsx", index=False)

# ============================================================
# 3. DECISION SCORE UNTUK NSCLC DAN SCLC
# ============================================================

def decision_score_for_target_network(
    df_perf,
    topology_df,
    target_dataset,
    benchmark_datasets,
    topology_features,
    performance_col="PC1_norm",
    top_k_benchmark=None
):
    # Hitung jarak target terhadap seluruh benchmark
    distance_df = compute_topological_distance(
        topology_df=topology_df,
        target_dataset=target_dataset,
        reference_datasets=benchmark_datasets,
        topology_features=topology_features,
        fit_scaler_on_reference=True
    )

    # Opsional: hanya gunakan k benchmark terdekat
    if top_k_benchmark is not None:
        distance_df = (
            distance_df
            .sort_values("Topology_Distance", ascending=True)
            .head(top_k_benchmark)
            .copy()
        )

    # Ubah jarak menjadi bobot
    distance_weight_df = add_inverse_distance_weight(distance_df)

    # Hitung decision score
    decision = compute_decision_score_from_references(
        df_perf=df_perf,
        distance_weight_df=distance_weight_df,
        target_dataset=target_dataset,
        performance_col=performance_col
    )

    decision["Target_Network"] = target_dataset

    decision = decision[
        ["Target_Network", "Predicted_Rank", "Model", "Decision_Score"]
    ]

    return decision, distance_weight_df


all_decision_results = []
all_target_weights = []

for target in target_datasets:

    decision_target, weight_target = decision_score_for_target_network(
        df_perf=df_perf,
        topology_df=topology_df,
        target_dataset=target,
        benchmark_datasets=benchmark_datasets,
        topology_features=topology_features,
        performance_col="PC1_norm",
        top_k_benchmark=None   # gunakan seluruh benchmark
    )

    all_decision_results.append(decision_target)
    all_target_weights.append(weight_target)

decision_score_df = pd.concat(all_decision_results, ignore_index=True)
target_weight_df = pd.concat(all_target_weights, ignore_index=True)

print("=== Bobot benchmark untuk NSCLC dan SCLC ===")
display(target_weight_df)

print("=== Decision score seluruh algoritma ===")
display(decision_score_df)

print("=== Top 3 algoritma kandidat per jaringan ===")
top3_candidate = (
    decision_score_df
    .sort_values(["Target_Network", "Predicted_Rank"])
    .groupby("Target_Network", group_keys=False)
    .head(3)
)

display(top3_candidate)

decision_score_df.to_excel("decision_score_nsclc_sclc_all_algorithms.xlsx", index=False)
target_weight_df.to_excel("decision_score_nsclc_sclc_benchmark_weights.xlsx", index=False)
top3_candidate.to_excel("top3_candidate_algorithms_nsclc_sclc.xlsx", index=False)

import json
import pandas as pd
import numpy as np

# ==============================
# 1. File input
# ==============================
files = {
    "PSO-LPA": "/content/drive/MyDrive/dataset/Tesis/pubtator/nsclc_pso_lpa_20runs_compact_summary.json",
    "Fuzzy LPA": "/content/drive/MyDrive/dataset/Tesis/pubtator/nsclc_fuzzy_lpa_20runs_compact_summary.json",
    "DPSO-Fuzzy": "/content/drive/MyDrive/dataset/Tesis/pubtator/nsclc_dpso_fuzzy_20runs_compact_summary.json"
}

rows = []

for algo, path in files.items():
    with open(path, "r") as f:
        data = json.load(f)

    rows.append({
        "algorithm": algo,
        "mean_fuzzy_modularity": data["mean_fuzzy_modularity"],
        "mean_stability": data["mean_stability"],
        "mean_entropy": data["mean_entropy"],
        "mean_composite": data["mean_composite"],
        "mean_num_overlapping_nodes": data["mean_num_overlapping_nodes"]
    })

df = pd.DataFrame(rows)

print("=== Data Awal ===")
print(df)


# ==============================
# 2. Fungsi normalisasi
# ==============================
def normalize_benefit(x):
    return (x - x.min()) / (x.max() - x.min() + 1e-12)

def normalize_cost(x):
    return (x.max() - x) / (x.max() - x.min() + 1e-12)


# ==============================
# 3. Normalisasi metrik
# ==============================
df_norm = df.copy()

# Benefit criteria
df_norm["norm_composite"] = normalize_benefit(df["mean_composite"])
df_norm["norm_fuzzy_modularity"] = normalize_benefit(df["mean_fuzzy_modularity"])
df_norm["norm_stability"] = normalize_benefit(df["mean_stability"])

# Cost criteria
df_norm["norm_low_entropy"] = normalize_cost(df["mean_entropy"])

# Overlap selectivity:
# jumlah overlapping node lebih sedikit dianggap lebih selektif
df_norm["norm_overlap_selectivity"] = normalize_cost(df["mean_num_overlapping_nodes"])


# ==============================
# 4. Purpose-oriented score
# ==============================
# Bobot disesuaikan dengan tujuan penelitian:
# fokus utama = kualitas komunitas + selektivitas overlapping

weights = {
    "norm_composite": 0.20,
    "norm_overlap_selectivity": 0.65,
    "norm_fuzzy_modularity": 0.05,
    "norm_stability": 0.10
}

df_norm["purpose_score"] = (
    weights["norm_composite"] * df_norm["norm_composite"] +
    weights["norm_overlap_selectivity"] * df_norm["norm_overlap_selectivity"] +
    weights["norm_fuzzy_modularity"] * df_norm["norm_fuzzy_modularity"] +
    weights["norm_stability"] * df_norm["norm_stability"]
)

df_norm["rank"] = df_norm["purpose_score"].rank(
    ascending=False,
    method="dense"
).astype(int)

df_rank = df_norm.sort_values("rank")

print("\n=== Ranking Berbasis Tujuan Identifikasi Overlapping Disease ===")
print(df_rank[[
    "rank",
    "algorithm",
    "mean_composite",
    "mean_num_overlapping_nodes",
    "mean_fuzzy_modularity",
    "mean_stability",
    "purpose_score"
]])

df_rank.to_csv("/content/drive/MyDrive/dataset/Tesis/pubtator/purpose_oriented_ranking_nsclc.csv", index=False)
print("\nHasil ranking disimpan ke: purpose_oriented_ranking_nsclc.csv")

import json
import pandas as pd
import numpy as np

# ==============================
# 1. File input
# ==============================
files = {
    "PSO-LPA": "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc_pso_lpa_20runs_compact_summary.json",
    "Fuzzy LPA": "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc_fuzzy_lpa_20runs_compact_summary.json",
    "DPSO-Fuzzy": "/content/drive/MyDrive/dataset/Tesis/pubtator/sclc_dpso_fuzzy_20runs_compact_summary.json"
}

rows = []

for algo, path in files.items():
    with open(path, "r") as f:
        data = json.load(f)

    rows.append({
        "algorithm": algo,
        "mean_fuzzy_modularity": data["mean_fuzzy_modularity"],
        "mean_stability": data["mean_stability"],
        "mean_entropy": data["mean_entropy"],
        "mean_composite": data["mean_composite"],
        "mean_num_overlapping_nodes": data["mean_num_overlapping_nodes"]
    })

df = pd.DataFrame(rows)

print("=== Data Awal ===")
print(df)


# ==============================
# 2. Fungsi normalisasi
# ==============================
def normalize_benefit(x):
    return (x - x.min()) / (x.max() - x.min() + 1e-12)

def normalize_cost(x):
    return (x.max() - x) / (x.max() - x.min() + 1e-12)


# ==============================
# 3. Normalisasi metrik
# ==============================
df_norm = df.copy()

# Benefit criteria
df_norm["norm_composite"] = normalize_benefit(df["mean_composite"])
df_norm["norm_fuzzy_modularity"] = normalize_benefit(df["mean_fuzzy_modularity"])
df_norm["norm_stability"] = normalize_benefit(df["mean_stability"])

# Cost criteria
df_norm["norm_low_entropy"] = normalize_cost(df["mean_entropy"])

# Overlap selectivity:
# jumlah overlapping node lebih sedikit dianggap lebih selektif
df_norm["norm_overlap_selectivity"] = normalize_cost(df["mean_num_overlapping_nodes"])


# ==============================
# 4. Purpose-oriented score
# ==============================
# Bobot disesuaikan dengan tujuan penelitian:
# fokus utama = kualitas komunitas + selektivitas overlapping

weights = {
    "norm_composite": 0.40,
    "norm_overlap_selectivity": 0.40,
    "norm_fuzzy_modularity": 0.10,
    "norm_stability": 0.10
}

df_norm["purpose_score"] = (
    weights["norm_composite"] * df_norm["norm_composite"] +
    weights["norm_overlap_selectivity"] * df_norm["norm_overlap_selectivity"] +
    weights["norm_fuzzy_modularity"] * df_norm["norm_fuzzy_modularity"] +
    weights["norm_stability"] * df_norm["norm_stability"]
)

df_norm["rank"] = df_norm["purpose_score"].rank(
    ascending=False,
    method="dense"
).astype(int)

df_rank = df_norm.sort_values("rank")

print("\n=== Ranking Berbasis Tujuan Identifikasi Overlapping Disease ===")
print(df_rank[[
    "rank",
    "algorithm",
    "mean_composite",
    "mean_num_overlapping_nodes",
    "mean_fuzzy_modularity",
    "mean_stability",
    "purpose_score"
]])

df_rank.to_csv("/content/drive/MyDrive/dataset/Tesis/pubtator/purpose_oriented_ranking_sclc.csv", index=False)
print("\nHasil ranking disimpan ke: purpose_oriented_ranking_sclc.csv")